import Foundation
import PDFKit
import GRDB

/// On-device full-text search over the library.
/// Documents are chunked (heading-aware for markdown, sentence-boundary for others)
/// and stored in search.sqlite on import; search uses FTS5 BM25 keyword ranking.
/// No embeddings or vector index — the chat agent drives retrieval by issuing queries.
final class FTSIndexService: @unchecked Sendable {
    let ftsDB: FTSDatabase
    let catalogDBQueue: DatabaseQueue

    static func create(
        ftsDB: FTSDatabase,
        catalogDBQueue: DatabaseQueue
    ) -> FTSIndexService {
        FTSIndexService(ftsDB: ftsDB, catalogDBQueue: catalogDBQueue)
    }

    private init(ftsDB: FTSDatabase, catalogDBQueue: DatabaseQueue) {
        self.ftsDB = ftsDB
        self.catalogDBQueue = catalogDBQueue
    }

    // MARK: - Public Index API

    /// Index an item by type. Routes to the appropriate text extractor and chunker.
    func indexItem(itemId: String, contentType: String, storageKey: String, attStorageKey: String, fileName: String) async {
        // Skip if already processed (has chunks, or was attempted and yielded none).
        if (try? ftsDB.isProcessed(itemId: itemId)) == true {
            return
        }

        let chunks = await extractChunks(
            itemId: itemId,
            contentType: contentType,
            storageKey: storageKey,
            attStorageKey: attStorageKey,
            fileName: fileName
        )

        if chunks.isEmpty {
            // Mark as processed anyway (0 chunks) so it isn't retried every launch and
            // doesn't show as perpetually "remaining" in settings. Likely needs OCR.
            Log.info(Log.fts, "No text to index for item \(itemId) — marking skipped")
        }

        storeChunks(itemId: itemId, chunks: chunks)
    }

    // MARK: - Text Extraction

    /// Extract all chunks for an item across its abstract and primary attachment.
    private func extractChunks(itemId: String, contentType: String, storageKey: String, attStorageKey: String, fileName: String) async -> [ContentChunker.Chunk] {
        var chunks = await extractAbstract(itemId: itemId)

        let fileURL = CatalogDatabase.attachmentFileURL(
            itemStorageKey: storageKey,
            attachmentStorageKey: attStorageKey,
            fileName: fileName
        )
        let attDir = CatalogDatabase.attachmentDirectory(
            itemStorageKey: storageKey,
            attachmentStorageKey: attStorageKey
        )

        switch contentType {
        case "pdf":
            chunks += extractPDFChunks(pdfURL: fileURL, attachmentDir: attDir)
        case "html":
            chunks += extractHTMLChunks(attachmentDir: attDir, htmlURL: fileURL)
        case "markdown":
            chunks += extractMarkdownChunks(fileURL: fileURL)
        case "link":
            chunks += extractEmbedTextChunks(attachmentDir: attDir)
        default:
            break
        }

        return chunks
    }

    /// Extract abstract from catalog.db citations table if available.
    private func extractAbstract(itemId: String) async -> [ContentChunker.Chunk] {
        let abstract: String? = try? await catalogDBQueue.read { db in
            try String.fetchOne(db, sql: "SELECT abstract FROM citations WHERE item_id = ?", arguments: [itemId])
        }
        guard let abstract, !abstract.isEmpty else { return [] }
        return [ContentChunker.Chunk(text: abstract, type: "abstract", pageStart: nil, pageEnd: nil)]
    }

    /// Extract chunks from a PDF document.
    /// Prefers structured content.md (heading-aware chunking) over raw PDFKit text.
    private func extractPDFChunks(pdfURL: URL, attachmentDir: URL) -> [ContentChunker.Chunk] {
        // Prefer content.md generated by pdf-oxide (heading-aware chunking)
        let mdURL = attachmentDir.appendingPathComponent("content.md")
        if let md = try? String(contentsOf: mdURL, encoding: .utf8), !md.isEmpty {
            return ContentChunker.chunkMarkdown(md)
        }

        // Fallback: PDFKit page text with plain text chunking
        guard let pdfDoc = PDFDocument(url: pdfURL) else {
            Log.error(Log.fts, "Cannot open PDF: \(pdfURL.lastPathComponent)")
            return []
        }
        var chunks: [ContentChunker.Chunk] = []
        for pageIndex in 0..<pdfDoc.pageCount {
            guard let page = pdfDoc.page(at: pageIndex), let text = page.string, !text.isEmpty else { continue }
            chunks += ContentChunker.chunkPlainText(text, type: "page", pageStart: pageIndex, pageEnd: pageIndex)
        }
        return chunks
    }

    /// Extract chunks from an HTML document: prefer content.md (heading-aware), fall back to HTML.
    private func extractHTMLChunks(attachmentDir: URL, htmlURL: URL) -> [ContentChunker.Chunk] {
        let mdURL = attachmentDir.appendingPathComponent("content.md")

        if let md = try? String(contentsOf: mdURL, encoding: .utf8), !md.isEmpty {
            return ContentChunker.chunkMarkdown(md)
        }

        if let data = try? Data(contentsOf: htmlURL) {
            let text = HTMLTextExtractor.extractText(from: data)
            if !text.isEmpty {
                return ContentChunker.chunkPlainText(text)
            }
        }

        return []
    }

    /// Extract chunks from a markdown file using heading-aware chunking.
    private func extractMarkdownChunks(fileURL: URL) -> [ContentChunker.Chunk] {
        guard let text = try? String(contentsOf: fileURL, encoding: .utf8), !text.isEmpty else {
            return []
        }
        return ContentChunker.chunkMarkdown(text)
    }

    /// Extract chunks from all .md and .txt files in an embed's attachment directory.
    private func extractEmbedTextChunks(attachmentDir: URL) -> [ContentChunker.Chunk] {
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(at: attachmentDir, includingPropertiesForKeys: nil) else {
            return []
        }

        var chunks: [ContentChunker.Chunk] = []
        for file in files.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            let ext = file.pathExtension.lowercased()
            guard ext == "md" || ext == "txt" else { continue }
            guard let text = try? String(contentsOf: file, encoding: .utf8), !text.isEmpty else { continue }

            if ext == "md" {
                chunks += ContentChunker.chunkMarkdown(text)
            } else {
                chunks += ContentChunker.chunkPlainText(text)
            }
        }
        return chunks
    }

    // MARK: - Store

    private func storeChunks(itemId: String, chunks: [ContentChunker.Chunk]) {
        let now = Date().iso8601String
        let records = chunks.map { chunk in
            FTSChunk(
                id: nil,
                itemId: itemId,
                chunkType: chunk.type,
                pageStart: chunk.pageStart,
                pageEnd: chunk.pageEnd,
                chunkText: chunk.text,
                tokenCount: ContentChunker.estimateTokenCount(chunk.text),
                createdAt: now
            )
        }
        do {
            try ftsDB.storeChunks(records, itemId: itemId, indexedAt: now)
            Log.info(Log.fts, "Indexed \(records.count) chunks for item \(itemId)")
        } catch {
            Log.error(Log.fts, "Failed to save chunk records for item \(itemId): \(error)")
        }
    }

    // MARK: - Search

    struct SearchResult: Sendable {
        let itemId: String
        let score: Double
        let excerpt: String
        let chunkType: String
        let pageStart: Int?
        let pageEnd: Int?
        /// Stable chunk rowid — the citable ID. The model cites `?c=<chunkId>` and
        /// the host resolves it back to the chunk's page + verbatim text, so a
        /// citation never depends on the model reproducing an exact quote.
        let chunkId: Int64?
    }

    /// The chunks covering a 0-based page of an item (PDF), for injecting the open
    /// page as citable `?c=` passages. Empty when the item isn't indexed.
    func currentPageChunks(itemId: String, page: Int) async -> [FTSChunk] {
        do {
            return try ftsDB.fetchChunks(forItemId: itemId, page: page)
        } catch {
            Log.error(Log.fts, "Failed to fetch current-page chunks: \(error)")
            return []
        }
    }

    /// All chunks of a non-paginated item (HTML / markdown / web), for injecting its
    /// body as citable `?c=` passages. Capped to keep the prompt bounded. Empty when
    /// the item isn't indexed.
    func allChunks(itemId: String, limit: Int = 80) async -> [FTSChunk] {
        do {
            return try ftsDB.fetchAllChunks(forItemId: itemId, limit: limit)
        } catch {
            Log.error(Log.fts, "Failed to fetch all chunks: \(error)")
            return []
        }
    }

    /// Fetch full chunks by their stable ids, keyed by id. Used to resolve and
    /// validate `?c=<chunkId>` citations against ground-truth chunk text.
    func chunks(byIds ids: [Int64]) async -> [Int64: FTSChunk] {
        let unique = Array(Set(ids))
        guard !unique.isEmpty else { return [:] }
        do {
            let chunks = try ftsDB.fetchChunks(byIds: unique)
            return Dictionary(uniqueKeysWithValues: chunks.compactMap { c in c.id.map { ($0, c) } })
        } catch {
            Log.error(Log.fts, "Failed to fetch chunks for citation resolution: \(error)")
            return [:]
        }
    }

    /// Full-text BM25 search.
    /// - Parameters:
    ///   - itemIds: when non-nil, restricts the search to these items (scope filter).
    ///   - groupByItem: `true` collapses to the single best passage per item (library
    ///     list view); `false` returns the top individual passages in rank order, so the
    ///     agent can read several distinct page-anchored excerpts (research loop).
    func search(query: String, maxResults: Int = 10, itemIds: [String]? = nil, groupByItem: Bool = true) async -> [SearchResult] {
        let hits: [FTSDatabase.Hit]
        do {
            hits = try ftsDB.bm25Search(query: query, maxResults: maxResults * 3, itemIds: itemIds)
        } catch {
            Log.error(Log.fts, "Full-text search failed: \(error)")
            return []
        }

        guard !hits.isEmpty else { return [] }

        let chunks: [FTSChunk]
        do {
            chunks = try ftsDB.fetchChunks(byIds: hits.map(\.chunkId))
        } catch {
            Log.error(Log.fts, "Failed to fetch chunks: \(error)")
            return []
        }
        let chunkById = Dictionary(uniqueKeysWithValues: chunks.compactMap { c in c.id.map { ($0, c) } })

        // Build results in BM25 rank order (hits are already best-first), preferring the
        // snippet() window over a raw prefix.
        func makeResult(_ hit: FTSDatabase.Hit) -> SearchResult? {
            guard let chunk = chunkById[hit.chunkId] else { return nil }
            let excerpt = hit.snippet.isEmpty ? String(chunk.chunkText.prefix(300)) : hit.snippet
            return SearchResult(
                itemId: chunk.itemId,
                score: hit.score,
                excerpt: excerpt,
                chunkType: chunk.chunkType,
                pageStart: chunk.pageStart,
                pageEnd: chunk.pageEnd,
                chunkId: chunk.id
            )
        }

        if groupByItem {
            var bestByItem: [String: SearchResult] = [:]
            for hit in hits {
                guard let result = makeResult(hit) else { continue }
                if let existing = bestByItem[result.itemId] {
                    if result.score > existing.score { bestByItem[result.itemId] = result }
                } else {
                    bestByItem[result.itemId] = result
                }
            }
            return Array(bestByItem.values)
                .sorted { $0.score > $1.score }
                .prefix(maxResults)
                .map { $0 }
        }

        // Passages mode: keep rank order, return distinct top hits.
        var results: [SearchResult] = []
        for hit in hits {
            guard let result = makeResult(hit) else { continue }
            results.append(result)
            if results.count >= maxResults { break }
        }
        return results
    }

    // MARK: - Remove Chunks

    func removeChunks(forItemId itemId: String) async {
        do {
            try ftsDB.deleteChunks(forItemId: itemId)
        } catch {
            Log.error(Log.fts, "Failed to delete chunk records for item \(itemId): \(error)")
        }
    }

    // MARK: - Background Index All

    private struct IndexableItem {
        let itemId: String
        let storageKey: String
        let attStorageKey: String
        let fileName: String
        let contentType: String
    }

    /// Find unindexed items and index each one, recently opened first.
    func backgroundIndexAll() async {
        let processedIds: Set<String>
        do {
            processedIds = try ftsDB.processedItemIds()
        } catch {
            Log.error(Log.fts, "Failed to query processed items: \(error)")
            return
        }

        let allItems: [IndexableItem]
        do {
            allItems = try await fetchIndexableItems()
        } catch {
            Log.error(Log.fts, "Failed to query items: \(error)")
            return
        }

        let itemsToIndex = allItems.filter { !processedIds.contains($0.itemId) }

        guard !itemsToIndex.isEmpty else {
            Log.info(Log.fts, "All items already indexed")
            return
        }

        Log.info(Log.fts, "Background indexing \(itemsToIndex.count) items")

        for item in itemsToIndex {
            guard !Task.isCancelled else { break }
            await indexItem(
                itemId: item.itemId,
                contentType: item.contentType,
                storageKey: item.storageKey,
                attStorageKey: item.attStorageKey,
                fileName: item.fileName
            )
            try? await Task.sleep(for: .milliseconds(50))
        }

        Log.info(Log.fts, "Background indexing complete")
    }

    /// Second, lower-priority pass: OCR the image-only PDFs that the normal pass marked
    /// empty (0 chunks). Runs after `backgroundIndexAll` so plain text indexing isn't
    /// blocked by the much slower OCR. Each PDF is OCR'd at most once — items that stay
    /// blank are flagged so they're never reprocessed.
    func backgroundOCRBackfill() async {
        let pending: Set<String>
        do {
            pending = try ftsDB.ocrPendingItemIds()
        } catch {
            Log.error(Log.fts, "Failed to query OCR-pending items: \(error)")
            return
        }
        guard !pending.isEmpty else { return }

        let items: [IndexableItem]
        do {
            items = try await fetchIndexableItems(restrictedTo: Array(pending))
        } catch {
            Log.error(Log.fts, "Failed to query items for OCR backfill: \(error)")
            return
        }
        let pdfItems = items.filter { $0.contentType == "pdf" }
        guard !pdfItems.isEmpty else { return }

        Log.info(Log.fts, "OCR backfill: \(pdfItems.count) image-only PDF(s)")

        for item in pdfItems {
            guard !Task.isCancelled else { break }

            let fileURL = CatalogDatabase.attachmentFileURL(
                itemStorageKey: item.storageKey,
                attachmentStorageKey: item.attStorageKey,
                fileName: item.fileName
            )
            let chunks = PDFOCRService.recognizeChunks(pdfURL: fileURL)
            if !chunks.isEmpty {
                storeChunks(itemId: item.itemId, chunks: chunks)
                Log.info(Log.fts, "OCR indexed \(chunks.count) chunks for item \(item.itemId)")
            }
            try? ftsDB.markOCRAttempted(itemId: item.itemId)

            try? await Task.sleep(for: .milliseconds(100))
        }

        Log.info(Log.fts, "OCR backfill complete")
    }

    /// Re-index specific items by their IDs (e.g. "Index All Content" on a collection).
    func indexItems(_ itemIds: [String]) async {
        let itemsToIndex: [IndexableItem]
        do {
            itemsToIndex = try await fetchIndexableItems(restrictedTo: itemIds)
        } catch {
            Log.error(Log.fts, "Failed to query items for collection indexing: \(error)")
            return
        }

        Log.info(Log.fts, "Indexing \(itemsToIndex.count) items from collection")

        for item in itemsToIndex {
            guard !Task.isCancelled else { break }

            // Force re-index: storeChunks replaces existing chunks and re-marks the item
            // (even with 0 chunks), so previously-skipped items don't linger as remaining.
            let chunks = await extractChunks(
                itemId: item.itemId,
                contentType: item.contentType,
                storageKey: item.storageKey,
                attStorageKey: item.attStorageKey,
                fileName: item.fileName
            )
            storeChunks(itemId: item.itemId, chunks: chunks)

            try? await Task.sleep(for: .milliseconds(50))
        }

        Log.info(Log.fts, "Collection indexing complete")
    }

    /// Fetch indexable items from catalog.db, recently opened first.
    /// When `restrictedTo` is non-nil, only those item IDs are returned.
    private func fetchIndexableItems(restrictedTo itemIds: [String]? = nil) async throws -> [IndexableItem] {
        try await catalogDBQueue.read { db in
            var sql = """
                SELECT i.id, i.storage_key, a.storage_key AS att_key, a.file_name, a.content_type
                FROM items i
                JOIN attachments a ON a.item_id = i.id AND a.is_primary = 1
                WHERE a.content_type IN ('pdf', 'html', 'markdown', 'link')
                """
            var arguments = StatementArguments()
            if let itemIds {
                let placeholders = itemIds.map { _ in "?" }.joined(separator: ",")
                sql += " AND i.id IN (\(placeholders))"
                arguments = StatementArguments(itemIds)
            } else {
                sql += """
                     ORDER BY
                        CASE WHEN i.last_opened_at IS NOT NULL THEN 0 ELSE 1 END,
                        i.last_opened_at DESC,
                        i.created_at DESC
                    """
            }
            let rows = try Row.fetchAll(db, sql: sql, arguments: arguments)
            return rows.map { row in
                IndexableItem(
                    itemId: row["id"] as String,
                    storageKey: row["storage_key"] as String,
                    attStorageKey: row["att_key"] as String,
                    fileName: row["file_name"] as String,
                    contentType: row["content_type"] as String
                )
            }
        }
    }
}
