import Foundation
import PDFKit
import GRDB

/// On-device full-text search over the library.
/// Documents are chunked (heading-aware for markdown, sentence-boundary for others)
/// and stored in semantic.sqlite on import; search uses FTS5 BM25 keyword ranking.
/// No embeddings or vector index — the chat agent drives retrieval by issuing queries.
final class SemanticIndexService: @unchecked Sendable {
    let semanticDB: SemanticDatabase
    let catalogDBQueue: DatabaseQueue

    static func create(
        semanticDB: SemanticDatabase,
        catalogDBQueue: DatabaseQueue
    ) -> SemanticIndexService {
        SemanticIndexService(semanticDB: semanticDB, catalogDBQueue: catalogDBQueue)
    }

    private init(semanticDB: SemanticDatabase, catalogDBQueue: DatabaseQueue) {
        self.semanticDB = semanticDB
        self.catalogDBQueue = catalogDBQueue
    }

    // MARK: - Public Index API

    /// Index an item by type. Routes to the appropriate text extractor and chunker.
    func indexItem(itemId: String, contentType: String, storageKey: String, attStorageKey: String, fileName: String) async {
        // Skip if already indexed.
        if let count = try? semanticDB.chunkCount(forItemId: itemId), count > 0 {
            return
        }

        let chunks = await extractChunks(
            itemId: itemId,
            contentType: contentType,
            storageKey: storageKey,
            attStorageKey: attStorageKey,
            fileName: fileName
        )

        guard !chunks.isEmpty else {
            Log.info(Log.semantic, "No text to index for item \(itemId)")
            return
        }

        storeChunks(itemId: itemId, chunks: chunks)
    }

    // MARK: - Text Extraction

    /// Extract all chunks for an item across its abstract and primary attachment.
    private func extractChunks(itemId: String, contentType: String, storageKey: String, attStorageKey: String, fileName: String) async -> [ContentChunker.Chunk] {
        var chunks = await extractAbstract(itemId: itemId)

        let fileURL = CatalogDatabase.attachmentFileURL(
            itemStorageKey: storageKey,
            attachmentStorageKey: attStorageKey,
            fileName: fileName
        )
        let attDir = CatalogDatabase.attachmentDirectory(
            itemStorageKey: storageKey,
            attachmentStorageKey: attStorageKey
        )

        switch contentType {
        case "pdf":
            chunks += extractPDFChunks(pdfURL: fileURL, attachmentDir: attDir)
        case "html":
            chunks += extractHTMLChunks(attachmentDir: attDir, htmlURL: fileURL)
        case "markdown":
            chunks += extractMarkdownChunks(fileURL: fileURL)
        case "video", "link":
            chunks += extractEmbedTextChunks(attachmentDir: attDir)
        default:
            break
        }

        return chunks
    }

    /// Extract abstract from catalog.db citations table if available.
    private func extractAbstract(itemId: String) async -> [ContentChunker.Chunk] {
        let abstract: String? = try? await catalogDBQueue.read { db in
            try String.fetchOne(db, sql: "SELECT abstract FROM citations WHERE item_id = ?", arguments: [itemId])
        }
        guard let abstract, !abstract.isEmpty else { return [] }
        return [ContentChunker.Chunk(text: abstract, type: "abstract", pageStart: nil, pageEnd: nil)]
    }

    /// Extract chunks from a PDF document.
    /// Prefers structured content.md (heading-aware chunking) over raw PDFKit text.
    private func extractPDFChunks(pdfURL: URL, attachmentDir: URL) -> [ContentChunker.Chunk] {
        // Prefer content.md generated by pdf-oxide (heading-aware chunking)
        let mdURL = attachmentDir.appendingPathComponent("content.md")
        if let md = try? String(contentsOf: mdURL, encoding: .utf8), !md.isEmpty {
            return ContentChunker.chunkMarkdown(md)
        }

        // Fallback: PDFKit page text with plain text chunking
        guard let pdfDoc = PDFDocument(url: pdfURL) else {
            Log.error(Log.semantic, "Cannot open PDF: \(pdfURL.lastPathComponent)")
            return []
        }
        var chunks: [ContentChunker.Chunk] = []
        for pageIndex in 0..<pdfDoc.pageCount {
            guard let page = pdfDoc.page(at: pageIndex), let text = page.string, !text.isEmpty else { continue }
            chunks += ContentChunker.chunkPlainText(text, type: "page", pageStart: pageIndex, pageEnd: pageIndex)
        }
        return chunks
    }

    /// Extract chunks from an HTML document: prefer content.md (heading-aware), fall back to HTML.
    private func extractHTMLChunks(attachmentDir: URL, htmlURL: URL) -> [ContentChunker.Chunk] {
        let mdURL = attachmentDir.appendingPathComponent("content.md")

        if let md = try? String(contentsOf: mdURL, encoding: .utf8), !md.isEmpty {
            return ContentChunker.chunkMarkdown(md)
        }

        if let data = try? Data(contentsOf: htmlURL) {
            let text = HTMLTextExtractor.extractText(from: data)
            if !text.isEmpty {
                return ContentChunker.chunkPlainText(text)
            }
        }

        return []
    }

    /// Extract chunks from a markdown file using heading-aware chunking.
    private func extractMarkdownChunks(fileURL: URL) -> [ContentChunker.Chunk] {
        guard let text = try? String(contentsOf: fileURL, encoding: .utf8), !text.isEmpty else {
            return []
        }
        return ContentChunker.chunkMarkdown(text)
    }

    /// Extract chunks from all .md and .txt files in an embed's attachment directory.
    private func extractEmbedTextChunks(attachmentDir: URL) -> [ContentChunker.Chunk] {
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(at: attachmentDir, includingPropertiesForKeys: nil) else {
            return []
        }

        var chunks: [ContentChunker.Chunk] = []
        for file in files.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            let ext = file.pathExtension.lowercased()
            guard ext == "md" || ext == "txt" else { continue }
            guard let text = try? String(contentsOf: file, encoding: .utf8), !text.isEmpty else { continue }

            if ext == "md" {
                chunks += ContentChunker.chunkMarkdown(text)
            } else {
                chunks += ContentChunker.chunkPlainText(text)
            }
        }
        return chunks
    }

    // MARK: - Store

    private func storeChunks(itemId: String, chunks: [ContentChunker.Chunk]) {
        let now = Date().iso8601String
        let records = chunks.map { chunk in
            SemanticChunk(
                id: nil,
                itemId: itemId,
                chunkType: chunk.type,
                pageStart: chunk.pageStart,
                pageEnd: chunk.pageEnd,
                chunkText: chunk.text,
                tokenCount: ContentChunker.estimateTokenCount(chunk.text),
                createdAt: now
            )
        }
        do {
            try semanticDB.insertChunks(records)
            Log.info(Log.semantic, "Indexed \(records.count) chunks for item \(itemId)")
        } catch {
            Log.error(Log.semantic, "Failed to save chunk records for item \(itemId): \(error)")
        }
    }

    // MARK: - Search

    struct SearchResult: Sendable {
        let itemId: String
        let score: Double
        let excerpt: String
        let chunkType: String
        let pageStart: Int?
        let pageEnd: Int?
    }

    /// Full-text BM25 search, deduplicating by item_id (keep highest score).
    func search(query: String, maxResults: Int = 10) async -> [SearchResult] {
        let hits: [SemanticDatabase.Hit]
        do {
            hits = try semanticDB.bm25Search(query: query, maxResults: maxResults * 3)
        } catch {
            Log.error(Log.semantic, "Full-text search failed: \(error)")
            return []
        }

        guard !hits.isEmpty else { return [] }

        let chunkIds = hits.map(\.chunkId)
        let scoreMap = Dictionary(uniqueKeysWithValues: hits.map { ($0.chunkId, $0.score) })

        let chunks: [SemanticChunk]
        do {
            chunks = try semanticDB.fetchChunks(byIds: chunkIds)
        } catch {
            Log.error(Log.semantic, "Failed to fetch chunks: \(error)")
            return []
        }

        // Deduplicate by item_id, keeping highest score
        var bestByItem: [String: SearchResult] = [:]
        for chunk in chunks {
            guard let chunkId = chunk.id else { continue }
            let score = scoreMap[chunkId] ?? 0
            let result = SearchResult(
                itemId: chunk.itemId,
                score: score,
                excerpt: String(chunk.chunkText.prefix(300)),
                chunkType: chunk.chunkType,
                pageStart: chunk.pageStart,
                pageEnd: chunk.pageEnd
            )
            if let existing = bestByItem[chunk.itemId] {
                if score > existing.score {
                    bestByItem[chunk.itemId] = result
                }
            } else {
                bestByItem[chunk.itemId] = result
            }
        }

        return Array(bestByItem.values)
            .sorted { $0.score > $1.score }
            .prefix(maxResults)
            .map { $0 }
    }

    // MARK: - Remove Chunks

    func removeChunks(forItemId itemId: String) async {
        do {
            try semanticDB.deleteChunks(forItemId: itemId)
        } catch {
            Log.error(Log.semantic, "Failed to delete chunk records for item \(itemId): \(error)")
        }
    }

    // MARK: - Background Index All

    private struct IndexableItem {
        let itemId: String
        let storageKey: String
        let attStorageKey: String
        let fileName: String
        let contentType: String
    }

    /// Find unindexed items and index each one, recently opened first.
    func backgroundIndexAll() async {
        let indexedIds: Set<String>
        do {
            indexedIds = try semanticDB.indexedItemIds()
        } catch {
            Log.error(Log.semantic, "Failed to query indexed items: \(error)")
            return
        }

        let allItems: [IndexableItem]
        do {
            allItems = try await fetchIndexableItems()
        } catch {
            Log.error(Log.semantic, "Failed to query items: \(error)")
            return
        }

        let itemsToIndex = allItems.filter { !indexedIds.contains($0.itemId) }

        guard !itemsToIndex.isEmpty else {
            Log.info(Log.semantic, "All items already indexed")
            return
        }

        Log.info(Log.semantic, "Background indexing \(itemsToIndex.count) items")

        for item in itemsToIndex {
            guard !Task.isCancelled else { break }
            await indexItem(
                itemId: item.itemId,
                contentType: item.contentType,
                storageKey: item.storageKey,
                attStorageKey: item.attStorageKey,
                fileName: item.fileName
            )
            try? await Task.sleep(for: .milliseconds(50))
        }

        Log.info(Log.semantic, "Background indexing complete")
    }

    /// Re-index specific items by their IDs (e.g. "Index All Content" on a collection).
    func indexItems(_ itemIds: [String]) async {
        let itemsToIndex: [IndexableItem]
        do {
            itemsToIndex = try await fetchIndexableItems(restrictedTo: itemIds)
        } catch {
            Log.error(Log.semantic, "Failed to query items for collection indexing: \(error)")
            return
        }

        Log.info(Log.semantic, "Indexing \(itemsToIndex.count) items from collection")

        for item in itemsToIndex {
            guard !Task.isCancelled else { break }

            // Force re-index: delete existing chunks first.
            try? semanticDB.deleteChunks(forItemId: item.itemId)

            let chunks = await extractChunks(
                itemId: item.itemId,
                contentType: item.contentType,
                storageKey: item.storageKey,
                attStorageKey: item.attStorageKey,
                fileName: item.fileName
            )
            guard !chunks.isEmpty else { continue }
            storeChunks(itemId: item.itemId, chunks: chunks)

            try? await Task.sleep(for: .milliseconds(50))
        }

        Log.info(Log.semantic, "Collection indexing complete")
    }

    /// Fetch indexable items from catalog.db, recently opened first.
    /// When `restrictedTo` is non-nil, only those item IDs are returned.
    private func fetchIndexableItems(restrictedTo itemIds: [String]? = nil) async throws -> [IndexableItem] {
        try await catalogDBQueue.read { db in
            var sql = """
                SELECT i.id, i.storage_key, a.storage_key AS att_key, a.file_name, a.content_type
                FROM items i
                JOIN attachments a ON a.item_id = i.id AND a.is_primary = 1
                WHERE a.content_type IN ('pdf', 'html', 'markdown', 'video')
                """
            var arguments = StatementArguments()
            if let itemIds {
                let placeholders = itemIds.map { _ in "?" }.joined(separator: ",")
                sql += " AND i.id IN (\(placeholders))"
                arguments = StatementArguments(itemIds)
            } else {
                sql += """
                     ORDER BY
                        CASE WHEN i.last_opened_at IS NOT NULL THEN 0 ELSE 1 END,
                        i.last_opened_at DESC,
                        i.created_at DESC
                    """
            }
            let rows = try Row.fetchAll(db, sql: sql, arguments: arguments)
            return rows.map { row in
                IndexableItem(
                    itemId: row["id"] as String,
                    storageKey: row["storage_key"] as String,
                    attStorageKey: row["att_key"] as String,
                    fileName: row["file_name"] as String,
                    contentType: row["content_type"] as String
                )
            }
        }
    }
}
