/**
 * Emits both sides of the protocol from schema.ts.
 *
 *   bun protocol/generate.ts           write the files
 *   bun protocol/generate.ts --check   fail if the committed output is stale
 *
 * The Swift side is a FLAT struct per direction with every field optional --
 * that is the shape the shell already used, and it is exactly where drift hid:
 * a field added to one command was simply missing from the struct, and an
 * optional one failed silently. Generating the union of all fields makes that
 * impossible.
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { COMMANDS, EVENTS, PROTOCOL_VERSION, type Field, type FieldType, type Message } from "./schema.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const BANNER = "// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.\n" +
               "// Run `pnpm protocol:generate` after changing the schema.\n";

// --- TypeScript -----------------------------------------------------------

function zodType(t: FieldType): string {
  switch (t.k) {
    case "string": return "z.string()";
    case "int": return "z.number().int().positive()";
    case "bool": return "z.boolean()";
    case "json": return "z.record(z.string(), z.any())";
    case "enum": return `z.enum([${t.values.map((v) => `"${v}"`).join(", ")}])`;
    case "array": return `z.array(${zodType(t.of)})${t.min ? `.min(${t.min})` : ""}`;
    case "ref": return t.ts;
  }
}

function zodField(f: Field): string {
  let s = zodType(f.type);
  if (f.nullable) s += ".nullable()";
  if (f.default !== undefined) s += `.default(${f.default})`;
  else if (f.optional) s += ".optional()";
  return s;
}

function tsType(t: FieldType): string {
  switch (t.k) {
    case "string": return "string";
    case "int": return "number";
    case "bool": return "boolean";
    case "json": return "Record<string, unknown>";
    case "enum": return t.values.map((v) => `"${v}"`).join(" | ");
    case "array": return `${tsType(t.of)}[]`;
    case "ref": return t.ts;
  }
}

function emitTypeScript(): string {
  const out: string[] = [BANNER, 'import { z } from "zod";',
    'import { WireMessage, WireToolDef, type ProviderSummary, type EventToolCall, type PromptOption } from "./protocol.base.js";',
    "", `export const PROTOCOL_VERSION = ${PROTOCOL_VERSION};`, ""];

  out.push("// --- Commands (shell -> backend) ---------------------------------------", "");
  out.push("const id = z.string();", "");
  for (const c of COMMANDS) {
    if (c.doc) out.push(`/** ${c.doc} */`);
    if (c.fields.length === 0) {
      out.push(`export const ${c.name}Command = z.object({ id, type: z.literal("${c.type}") });`);
    } else {
      out.push(`export const ${c.name}Command = z.object({`, `  id,`, `  type: z.literal("${c.type}"),`);
      for (const f of c.fields) {
        if (f.doc) out.push(`  /** ${f.doc} */`);
        out.push(`  ${f.name}: ${zodField(f)},`);
      }
      out.push("});");
    }
    out.push("");
  }
  out.push("export const Command = z.discriminatedUnion(\"type\", [",
    ...COMMANDS.map((c) => `  ${c.name}Command,`), "]);",
    "export type Command = z.infer<typeof Command>;", "");

  out.push("// --- Events (backend -> shell) -----------------------------------------", "");
  out.push("export type Event =");
  for (const e of EVENTS) {
    const fields = e.fields.map((f) => {
      const opt = f.optional && f.default === undefined ? "?" : "";
      const nul = f.nullable ? " | null" : "";
      return `${f.name}${opt}: ${tsType(f.type)}${nul}`;
    });
    const body = [`id: string`, `type: "${e.type}"`, ...fields].join("; ");
    out.push(`  | { ${body} }`);
  }
  out[out.length - 1] += ";";
  out.push("");
  return out.join("\n");
}

// --- Swift ----------------------------------------------------------------

const SWIFT_RESERVED = new Set(["protocol", "default", "class", "struct", "enum", "case", "import", "extension"]);
const swiftName = (n: string) => (SWIFT_RESERVED.has(n) ? `\`${n}\`` : n);

function swiftType(t: FieldType, forDecoding: boolean): string {
  switch (t.k) {
    case "string": return "String";
    case "int": return "Int";
    case "bool": return "Bool";
    // Opaque JSON decodes through the passthrough enum and encodes through the wrapper.
    case "json": return forDecoding ? "[String: JSONFragment]" : "AnyJSONObject";
    case "enum": return "String";
    case "array": return `[${swiftType(t.of, forDecoding)}]`;
    case "ref": return t.swift;
  }
}

/** Union every message's fields into one flat struct, checking for type conflicts. */
function unionFields(messages: Message[], forDecoding: boolean): { name: string; type: string; doc: string }[] {
  const seen = new Map<string, { type: string; owners: string[]; doc: string }>();
  for (const m of messages) {
    for (const f of m.fields) {
      const ty = swiftType(f.type, forDecoding);
      const prev = seen.get(f.name);
      if (prev) {
        if (prev.type !== ty) {
          throw new Error(
            `field "${f.name}" has conflicting types across messages: ` +
            `${prev.type} (${prev.owners.join(", ")}) vs ${ty} (${m.type})`);
        }
        prev.owners.push(m.type);
      } else {
        seen.set(f.name, { type: ty, owners: [m.type], doc: f.doc ?? "" });
      }
    }
  }
  return [...seen].map(([name, v]) => ({ name, type: v.type, doc: v.owners.join(", ") }));
}

function emitSwift(): string {
  const out: string[] = [BANNER, "import Foundation", "",
    "enum GeneratedProtocol {", `    static let version = ${PROTOCOL_VERSION}`, "}", ""];

  out.push("/// Every command the shell can send. One flat struct: `type` selects which",
    "/// fields are meaningful, and JSONEncoder omits the nils.",
    "struct BackendCommand: Encodable {",
    "    var id: String", "    var type: String");
  for (const f of unionFields(COMMANDS, false)) {
    out.push(`    /// ${f.doc}`);
    out.push(`    var ${swiftName(f.name)}: ${f.type}?`);
  }
  out.push("}", "");

  out.push("/// Every event the backend can emit. Decoding is lenient by design: an",
    "/// unknown field is ignored, and a field belonging to another event type is nil.",
    "struct BackendEvent: Decodable {",
    "    var id: String",
    `    var type: String  // ${EVENTS.map((e) => e.type).join(" | ")}`);
  for (const f of unionFields(EVENTS, true)) {
    out.push(`    /// ${f.doc}`);
    out.push(`    var ${swiftName(f.name)}: ${f.type}?`);
  }
  out.push("}", "");
  return out.join("\n");
}

// --- Write / check --------------------------------------------------------

const outputs: [string, string][] = [
  [join(root, "backend/src/protocol.generated.ts"), emitTypeScript()],
  [join(root, "app/Services/Backend/BackendProtocol.generated.swift"), emitSwift()],
];

const check = process.argv.includes("--check");
let stale = false;
for (const [path, content] of outputs) {
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (current === content) {
    if (!check) console.log(`unchanged  ${path.replace(root + "/", "")}`);
    continue;
  }
  if (check) {
    console.error(`STALE  ${path.replace(root + "/", "")} — run \`pnpm protocol:generate\``);
    stale = true;
  } else {
    writeFileSync(path, content);
    console.log(`wrote      ${path.replace(root + "/", "")}`);
  }
}
if (check && stale) process.exit(1);
if (check) console.log("protocol: generated files are up to date");
