/**
 * Emits both sides of the JSON-RPC protocol from schema.ts.
 *
 *   bun protocol/generate.ts           write
 *   bun protocol/generate.ts --check   fail if the committed output is stale
 *
 * Per-method params/result structs replace the old flat all-optional struct.
 * That flat shape was where drift hid: a field belonging to one message was
 * indistinguishable from a field nobody had implemented yet.
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { METHODS, ERRORS, PROTOCOL_VERSION, type Field, type FieldType, type Method } from "./schema.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const BANNER =
  "// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.\n" +
  "// Run `pnpm protocol:generate` after changing the schema.\n";

const requests = METHODS.filter((m) => m.kind === "request");
const notifications = METHODS.filter((m) => m.kind === "notification");

// --- TypeScript -----------------------------------------------------------

function zodType(t: FieldType): string {
  switch (t.k) {
    case "string": return "z.string()";
    case "int": return "z.number().int().positive()";
    case "bool": return "z.boolean()";
    case "json": return "z.record(z.string(), z.any())";
    case "enum": return `z.enum([${t.values.map((v) => `"${v}"`).join(", ")}])`;
    case "array": return `z.array(${zodType(t.of)})${t.min ? `.min(${t.min})` : ""}`;
    case "ref": return t.ts;
  }
}
function zodField(f: Field): string {
  let s = zodType(f.type);
  if (f.nullable) s += ".nullable()";
  if (f.default !== undefined) s += `.default(${f.default})`;
  else if (f.optional) s += ".optional()";
  return s;
}
function tsType(t: FieldType): string {
  switch (t.k) {
    case "string": return "string";
    case "int": return "number";
    case "bool": return "boolean";
    case "json": return "Record<string, unknown>";
    case "enum": return t.values.map((v) => `"${v}"`).join(" | ");
    case "array": return `${tsType(t.of)}[]`;
    case "ref": return t.ts;
  }
}
function tsShape(fields: Field[], indent = "  "): string {
  if (fields.length === 0) return "Record<string, never>";
  const body = fields.map((f) => {
    const opt = f.optional && f.default === undefined ? "?" : "";
    const nul = f.nullable ? " | null" : "";
    const doc = f.doc ? `${indent}/** ${f.doc} */\n` : "";
    return `${doc}${indent}${f.name}${opt}: ${tsType(f.type)}${nul};`;
  }).join("\n");
  return `{\n${body}\n}`;
}

function emitTypeScript(): string {
  const o: string[] = [BANNER, 'import { z } from "zod";',
    'import { WireMessage, WireToolDef, WordLookup, Annotation, type ProviderSummary, type EventToolCall, type PromptOption } from "./protocol.base.js";',
    '// eslint-disable-next-line @typescript-eslint/no-unused-vars -- refs used by generated shapes',
    "", `export const PROTOCOL_VERSION = ${PROTOCOL_VERSION};`, ""];

  o.push("/** JSON-RPC 2.0 error codes. Below -32000 is ours; the rest is the spec's. */");
  o.push("export const RpcError = {");
  for (const e of ERRORS) o.push(`  /** ${e.doc} */\n  ${e.name}: ${e.code},`);
  o.push("} as const;", "export type RpcErrorCode = (typeof RpcError)[keyof typeof RpcError];", "");

  o.push("// --- Params / results by method ----------------------------------------", "");
  o.push("// zod schemas exist only for messages the shell SENDS us: you validate");
  o.push("// what you receive, not what you produce. Server-originated messages get");
  o.push("// plain types, which also keeps refs like ProviderSummary type-only.", "");
  for (const m of METHODS) {
    if (m.doc) o.push(`/** \`${m.name}\` — ${m.doc} */`);
    else o.push(`/** \`${m.name}\` */`);
    if (m.from === "client") {
      o.push(`export const ${m.type}Params = z.object({`);
      for (const f of m.params) {
        if (f.doc) o.push(`  /** ${f.doc} */`);
        o.push(`  ${f.name}: ${zodField(f)},`);
      }
      o.push("});");
      o.push(`export type ${m.type}Params = z.infer<typeof ${m.type}Params>;`);
      if (m.kind === "request") {
        o.push(`export type ${m.type}Result = ${tsShape(m.result ?? [])};`);
      }
    } else {
      o.push(`export type ${m.type}Params = ${tsShape(m.params)};`);
      if (m.kind === "request") {
        // We send it; the shell's answer is what we must be able to read.
        o.push(`export type ${m.type}Result = ${tsShape(m.result ?? [])};`);
      }
    }
    o.push("");
  }

  o.push("// --- Dispatch tables ---------------------------------------------------", "");
  o.push("/** Requests the shell sends us, by method name. */");
  o.push("export const ClientRequests = {");
  for (const m of requests.filter((m) => m.from === "client")) o.push(`  "${m.name}": ${m.type}Params,`);
  o.push("} as const;", "");
  o.push("/** Notifications the shell sends us. */");
  o.push("export const ClientNotifications = {");
  for (const m of notifications.filter((m) => m.from === "client")) o.push(`  "${m.name}": ${m.type}Params,`);
  o.push("} as const;", "");
  o.push("export type ClientRequestMethod = keyof typeof ClientRequests;");
  o.push("export type ClientNotificationMethod = keyof typeof ClientNotifications;");
  o.push("/** Maps each client request method to its result type. */");
  o.push("export interface ClientRequestResults {");
  for (const m of requests.filter((m) => m.from === "client")) o.push(`  "${m.name}": ${m.type}Result;`);
  o.push("}", "");
  o.push("/** Requests we send to the shell. */");
  o.push("export type ServerRequestMethod =");
  for (const m of requests.filter((m) => m.from === "server")) o.push(`  | "${m.name}"`);
  o.push("  ;", "");
  o.push("/** Notifications we send to the shell. */");
  o.push("export type ServerNotificationMethod =");
  for (const m of notifications.filter((m) => m.from === "server")) o.push(`  | "${m.name}"`);
  o.push("  ;", "");
  return o.join("\n");
}

// --- Swift ----------------------------------------------------------------

const SWIFT_RESERVED = new Set(["protocol", "default", "class", "struct", "enum", "case",
                                "import", "extension", "return", "func", "let", "var", "id"]);
const swiftName = (n: string) => (SWIFT_RESERVED.has(n) ? `\`${n}\`` : n);

function swiftType(t: FieldType, decoding: boolean): string {
  switch (t.k) {
    case "string": return "String";
    case "int": return "Int";
    case "bool": return "Bool";
    case "json": return decoding ? "[String: JSONFragment]" : "AnyJSONObject";
    case "enum": return "String";
    case "array": return `[${swiftType(t.of, decoding)}]`;
    case "ref": return t.swift;
  }
}

function swiftStruct(name: string, fields: Field[], conformance: string, decoding: boolean): string[] {
  const o = [`    struct ${name}: ${conformance} {`];
  if (fields.length === 0) {
    o.push("        init() {}");
  } else {
    for (const f of fields) {
      if (f.doc) o.push(`        /// ${f.doc}`);
      // Anything with a default is optional on the wire: the peer fills it in.
      const opt = f.optional || f.nullable || f.default !== undefined ? "?" : "";
      o.push(`        var ${swiftName(f.name)}: ${swiftType(f.type, decoding)}${opt}`);
    }
  }
  o.push("    }");
  return o;
}

function emitSwift(): string {
  const o: string[] = [BANNER, "import Foundation", "",
    "/// The sidecar protocol: JSON-RPC 2.0 over newline-delimited stdio.",
    "///",
    "/// Per-method params and results, rather than one flat struct of optionals.",
    "/// Reverse calls (tool/execute, oauth/prompt) are ordinary requests in the",
    "/// other direction, so they need no separate machinery.",
    "enum RPC {",
    `    static let version = ${PROTOCOL_VERSION}`, ""];

  o.push("    /// JSON-RPC error codes. The shell branches on these: re-authenticate",
    "    /// is a different affordance from retry, and the old single error string",
    "    /// could not distinguish them.",
    "    enum ErrorCode {");
  for (const e of ERRORS) {
    o.push(`        /// ${e.doc}`);
    o.push(`        static let ${e.name} = ${e.code}`);
  }
  o.push("    }", "");

  o.push("    /// Method names, so call sites never spell one by hand.", "    enum Method {");
  for (const m of METHODS) {
    const ident = m.type.charAt(0).toLowerCase() + m.type.slice(1);
    o.push(`        static let ${ident} = "${m.name}"`);
  }
  o.push("    }", "");

  for (const m of METHODS) {
    const outbound = m.from === "client";
    o.push(`    // MARK: ${m.name}`);
    if (m.doc) o.push(`    /// ${m.doc}`);
    o.push(...swiftStruct(`${m.type}Params`, m.params,
      outbound ? "Encodable" : "Decodable", !outbound));
    if (m.kind === "request") {
      o.push(...swiftStruct(`${m.type}Result`, m.result ?? [],
        outbound ? "Decodable" : "Encodable", outbound));
    }
    o.push("");
  }
  o.push("}", "");
  return o.join("\n");
}

// --- Write / check --------------------------------------------------------

const outputs: [string, string][] = [
  [join(root, "backend/src/protocol.generated.ts"), emitTypeScript()],
  [join(root, "app/Services/Backend/BackendProtocol.generated.swift"), emitSwift()],
];

const check = process.argv.includes("--check");
let stale = false;
for (const [path, content] of outputs) {
  const rel = path.replace(root + "/", "");
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (current === content) { if (!check) console.log(`unchanged  ${rel}`); continue; }
  if (check) { console.error(`STALE  ${rel} — run \`pnpm protocol:generate\``); stale = true; }
  else { writeFileSync(path, content); console.log(`wrote      ${rel}`); }
}
if (check && stale) process.exit(1);
if (check) console.log("protocol: generated files are up to date");
