// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.
// Run `pnpm protocol:generate` after changing the schema.

import { z } from "zod";
import { WireMessage, WireToolDef, WordLookup, type ProviderSummary, type EventToolCall, type PromptOption } from "./protocol.base.js";
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- refs used by generated shapes

export const PROTOCOL_VERSION = 5;

/** JSON-RPC 2.0 error codes. Below -32000 is ours; the rest is the spec's. */
export const RpcError = {
  /** Malformed JSON (spec). */
  parseError: -32700,
  /** Not a valid Request object (spec). */
  invalidRequest: -32600,
  /** Unknown method (spec). */
  methodNotFound: -32601,
  /** Params failed validation (spec). */
  invalidParams: -32602,
  /** Unhandled failure (spec). */
  internalError: -32603,
  /** Rejected credentials; offer re-authentication. */
  providerAuth: -31001,
  /** Throttled; offer retry, `data.retryAfter` when known. */
  providerRateLimit: -31002,
  /** Unreachable or failing; offer another provider. */
  providerUnavailable: -31003,
  /** Ended by $/cancelRequest. */
  cancelled: -31004,
  /** The shell could not run the tool. */
  toolFailed: -31005,
  /** No credential or model configured for the provider. */
  notConfigured: -31006,
} as const;
export type RpcErrorCode = (typeof RpcError)[keyof typeof RpcError];

// --- Params / results by method ----------------------------------------

// zod schemas exist only for messages the shell SENDS us: you validate
// what you receive, not what you produce. Server-originated messages get
// plain types, which also keeps refs like ProviderSummary type-only.

/** `ping` — Handshake. The shell refuses to proceed on a protocol mismatch. */
export const PingParams = z.object({
});
export type PingParams = z.infer<typeof PingParams>;
export type PingResult = {
  protocol: number;
  backend: string;
};

/** `complete` — One-shot completion. Streams chat/delta, resolves when finished. */
export const CompleteParams = z.object({
  providerId: z.string(),
  model: z.string(),
  system: z.string().optional(),
  messages: z.array(WireMessage).min(1),
  maxTokens: z.number().int().positive().default(4096),
  /** Explicit key for Test Connection, before anything is saved. */
  apiKey: z.string().optional(),
  baseUrl: z.string().optional(),
});
export type CompleteParams = z.infer<typeof CompleteParams>;
export type CompleteResult = {
  stopReason: string;
};

/** `chat` — The agentic loop. Streams chat/* notifications and calls tool/execute back. */
export const ChatParams = z.object({
  providerId: z.string(),
  model: z.string(),
  system: z.string().optional(),
  messages: z.array(WireMessage).min(1),
  tools: z.array(WireToolDef).default([]),
  maxTokens: z.number().int().positive().default(8192),
  reasoning: z.enum(["minimal", "low", "medium", "high", "xhigh", "max"]).optional(),
  maxIterations: z.number().int().positive().default(10),
});
export type ChatParams = z.infer<typeof ChatParams>;
export type ChatResult = {
  stopReason: string;
};

/** `providers/list` */
export const ProvidersListParams = z.object({
});
export type ProvidersListParams = z.infer<typeof ProvidersListParams>;
export type ProvidersListResult = {
  providers: ProviderSummary[];
};

/** `credentials/set` */
export const CredentialsSetParams = z.object({
  providerId: z.string(),
  key: z.string(),
});
export type CredentialsSetParams = z.infer<typeof CredentialsSetParams>;
export type CredentialsSetResult = Record<string, never>;

/** `credentials/get` */
export const CredentialsGetParams = z.object({
  providerId: z.string(),
});
export type CredentialsGetParams = z.infer<typeof CredentialsGetParams>;
export type CredentialsGetResult = {
  /** null when the provider has no key stored. */
  apiKey?: string | null;
};

/** `credentials/delete` */
export const CredentialsDeleteParams = z.object({
  providerId: z.string(),
});
export type CredentialsDeleteParams = z.infer<typeof CredentialsDeleteParams>;
export type CredentialsDeleteResult = Record<string, never>;

/** `oauth/login` — Streams oauth/notify and calls oauth/prompt back for user input. */
export const OAuthLoginParams = z.object({
  providerId: z.string(),
});
export type OAuthLoginParams = z.infer<typeof OAuthLoginParams>;
export type OAuthLoginResult = Record<string, never>;

/** `config/setBaseUrl` */
export const ConfigSetBaseUrlParams = z.object({
  providerId: z.string(),
  /** Absent clears the override. */
  baseUrl: z.string().optional(),
});
export type ConfigSetBaseUrlParams = z.infer<typeof ConfigSetBaseUrlParams>;
export type ConfigSetBaseUrlResult = Record<string, never>;

/** `config/setLocalUrl` */
export const ConfigSetLocalUrlParams = z.object({
  providerId: z.enum(["ollama", "lmstudio"]),
  baseUrl: z.string(),
});
export type ConfigSetLocalUrlParams = z.infer<typeof ConfigSetLocalUrlParams>;
export type ConfigSetLocalUrlResult = Record<string, never>;

/** `models/refresh` */
export const ModelsRefreshParams = z.object({
  providerId: z.string().optional(),
});
export type ModelsRefreshParams = z.infer<typeof ModelsRefreshParams>;
export type ModelsRefreshResult = {
  message?: string;
};

/** `prompts/compose` — The static half of the system prompt: base.md plus the named mixins. The shell appends live context afterwards -- that half cannot be a file. */
export const PromptsComposeParams = z.object({
  /** Mixin names, without .md, in the order they should appear. */
  mixins: z.array(z.string()).default([]),
});
export type PromptsComposeParams = z.infer<typeof PromptsComposeParams>;
export type PromptsComposeResult = {
  /** Empty when no prompt files were found. */
  text: string;
  /** Mixins that existed and were included. */
  used: string[];
  /** Every mixin this build carries. */
  available: string[];
};

/** `catalog/wordLookups/list` — One document's lookups, or every one when itemId is absent. Newest first. */
export const WordLookupsListParams = z.object({
  itemId: z.string().optional(),
});
export type WordLookupsListParams = z.infer<typeof WordLookupsListParams>;
export type WordLookupsListResult = {
  lookups: WordLookup[];
};

/** `catalog/wordLookups/save` — Insert, replacing any prior lookup of the same word in the same document. */
export const WordLookupsSaveParams = z.object({
  lookup: WordLookup,
});
export type WordLookupsSaveParams = z.infer<typeof WordLookupsSaveParams>;
export type WordLookupsSaveResult = Record<string, never>;

/** `catalog/wordLookups/delete` */
export const WordLookupsDeleteParams = z.object({
  id: z.string(),
});
export type WordLookupsDeleteParams = z.infer<typeof WordLookupsDeleteParams>;
export type WordLookupsDeleteResult = Record<string, never>;

/** `catalog/wordLookups/clear` — Clear one document's history, or all of it when itemId is absent. */
export const WordLookupsClearParams = z.object({
  itemId: z.string().optional(),
});
export type WordLookupsClearParams = z.infer<typeof WordLookupsClearParams>;
export type WordLookupsClearResult = Record<string, never>;

/** `$/cancelRequest` — LSP's spelling. The peer fails the named request and anything it spawned. */
export const CancelRequestParams = z.object({
  id: z.string(),
});
export type CancelRequestParams = z.infer<typeof CancelRequestParams>;

/** `tool/execute` — The shell runs the tool and answers. Tools read local app state, so they cannot run in the sidecar. */
export type ToolExecuteParams = {
  /** Id of the request this belongs to. */
  token: string;
  name: string;
  args: Record<string, unknown>;
};
export type ToolExecuteResult = {
  content: string;
  isError: boolean;
};

/** `oauth/prompt` — Asks the shell for one piece of user input during a login. */
export type OAuthPromptParams = {
  /** Id of the request this belongs to. */
  token: string;
  promptType: "text" | "secret" | "select" | "manual_code";
  message: string;
  placeholder?: string;
  options?: PromptOption[];
};
export type OAuthPromptResult = {
  /** Absent means cancelled. */
  value?: string;
};

/** `chat/delta` */
export type ChatDeltaParams = {
  /** Id of the request this belongs to. */
  token: string;
  text: string;
};

/** `chat/thinking` */
export type ChatThinkingParams = {
  /** Id of the request this belongs to. */
  token: string;
  text: string;
};

/** `chat/assistant` — Authoritative snapshot of one iteration's assistant message. */
export type ChatAssistantParams = {
  /** Id of the request this belongs to. */
  token: string;
  text: string;
  thinking?: string;
  toolCalls: EventToolCall[];
};

/** `oauth/notify` */
export type OAuthNotifyParams = {
  /** Id of the request this belongs to. */
  token: string;
  kind: "info" | "auth_url" | "device_code" | "progress";
  message?: string;
  url?: string;
  userCode?: string;
  verificationUri?: string;
};

// --- Dispatch tables ---------------------------------------------------

/** Requests the shell sends us, by method name. */
export const ClientRequests = {
  "ping": PingParams,
  "complete": CompleteParams,
  "chat": ChatParams,
  "providers/list": ProvidersListParams,
  "credentials/set": CredentialsSetParams,
  "credentials/get": CredentialsGetParams,
  "credentials/delete": CredentialsDeleteParams,
  "oauth/login": OAuthLoginParams,
  "config/setBaseUrl": ConfigSetBaseUrlParams,
  "config/setLocalUrl": ConfigSetLocalUrlParams,
  "models/refresh": ModelsRefreshParams,
  "prompts/compose": PromptsComposeParams,
  "catalog/wordLookups/list": WordLookupsListParams,
  "catalog/wordLookups/save": WordLookupsSaveParams,
  "catalog/wordLookups/delete": WordLookupsDeleteParams,
  "catalog/wordLookups/clear": WordLookupsClearParams,
} as const;

/** Notifications the shell sends us. */
export const ClientNotifications = {
  "$/cancelRequest": CancelRequestParams,
} as const;

export type ClientRequestMethod = keyof typeof ClientRequests;
export type ClientNotificationMethod = keyof typeof ClientNotifications;
/** Maps each client request method to its result type. */
export interface ClientRequestResults {
  "ping": PingResult;
  "complete": CompleteResult;
  "chat": ChatResult;
  "providers/list": ProvidersListResult;
  "credentials/set": CredentialsSetResult;
  "credentials/get": CredentialsGetResult;
  "credentials/delete": CredentialsDeleteResult;
  "oauth/login": OAuthLoginResult;
  "config/setBaseUrl": ConfigSetBaseUrlResult;
  "config/setLocalUrl": ConfigSetLocalUrlResult;
  "models/refresh": ModelsRefreshResult;
  "prompts/compose": PromptsComposeResult;
  "catalog/wordLookups/list": WordLookupsListResult;
  "catalog/wordLookups/save": WordLookupsSaveResult;
  "catalog/wordLookups/delete": WordLookupsDeleteResult;
  "catalog/wordLookups/clear": WordLookupsClearResult;
}

/** Requests we send to the shell. */
export type ServerRequestMethod =
  | "tool/execute"
  | "oauth/prompt"
  ;

/** Notifications we send to the shell. */
export type ServerNotificationMethod =
  | "chat/delta"
  | "chat/thinking"
  | "chat/assistant"
  | "oauth/notify"
  ;
