// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.
// Run `pnpm protocol:generate` after changing the schema.

import { z } from "zod";
import { WireMessage, WireToolDef, type ProviderSummary, type EventToolCall, type PromptOption } from "./protocol.base.js";

export const PROTOCOL_VERSION = 2;

// --- Commands (shell -> backend) ---------------------------------------

const id = z.string();

export const PingCommand = z.object({ id, type: z.literal("ping") });

export const AbortCommand = z.object({ id, type: z.literal("abort") });

/** One-shot completion (no tool loop). */
export const CompleteCommand = z.object({
  id,
  type: z.literal("complete"),
  providerId: z.string(),
  model: z.string(),
  system: z.string().optional(),
  messages: z.array(WireMessage).min(1),
  maxTokens: z.number().int().positive().default(4096),
  /** Explicit key for Test Connection (verify before saving). */
  apiKey: z.string().optional(),
  baseUrl: z.string().optional(),
});

/** The agentic loop; calls back with tool_exec. */
export const ChatCommand = z.object({
  id,
  type: z.literal("chat"),
  providerId: z.string(),
  model: z.string(),
  system: z.string().optional(),
  messages: z.array(WireMessage).min(1),
  tools: z.array(WireToolDef).default([]),
  maxTokens: z.number().int().positive().default(8192),
  reasoning: z.enum(["minimal", "low", "medium", "high", "xhigh", "max"]).optional(),
  maxIterations: z.number().int().positive().default(10),
});

/** Answers a tool_exec event; `id` is the chat request id. */
export const ToolResultCommand = z.object({
  id,
  type: z.literal("tool_result"),
  callId: z.string(),
  content: z.string(),
  isError: z.boolean().default(false),
});

export const ListProvidersCommand = z.object({ id, type: z.literal("list_providers") });

export const SetApiKeyCommand = z.object({
  id,
  type: z.literal("set_api_key"),
  providerId: z.string(),
  key: z.string(),
});

export const GetApiKeyCommand = z.object({
  id,
  type: z.literal("get_api_key"),
  providerId: z.string(),
});

export const DeleteCredentialCommand = z.object({
  id,
  type: z.literal("delete_credential"),
  providerId: z.string(),
});

export const OAuthLoginCommand = z.object({
  id,
  type: z.literal("oauth_login"),
  providerId: z.string(),
});

/** Answers an oauth_prompt; `id` is the oauth_login request id. */
export const OAuthPromptResultCommand = z.object({
  id,
  type: z.literal("oauth_prompt_result"),
  promptId: z.string(),
  /** Absent = cancelled. */
  value: z.string().optional(),
});

export const SetBaseUrlCommand = z.object({
  id,
  type: z.literal("set_base_url"),
  providerId: z.string(),
  /** Absent = clear the override. */
  baseUrl: z.string().optional(),
});

export const SetLocalUrlCommand = z.object({
  id,
  type: z.literal("set_local_url"),
  providerId: z.enum(["ollama", "lmstudio"]),
  baseUrl: z.string(),
});

export const RefreshModelsCommand = z.object({
  id,
  type: z.literal("refresh_models"),
  providerId: z.string().optional(),
});

export const Command = z.discriminatedUnion("type", [
  PingCommand,
  AbortCommand,
  CompleteCommand,
  ChatCommand,
  ToolResultCommand,
  ListProvidersCommand,
  SetApiKeyCommand,
  GetApiKeyCommand,
  DeleteCredentialCommand,
  OAuthLoginCommand,
  OAuthPromptResultCommand,
  SetBaseUrlCommand,
  SetLocalUrlCommand,
  RefreshModelsCommand,
]);
export type Command = z.infer<typeof Command>;

// --- Events (backend -> shell) -----------------------------------------

export type Event =
  | { id: string; type: "response"; command: string; success: boolean; protocol?: number; backend?: string; message?: string; providers?: ProviderSummary[]; apiKey?: string | null }
  | { id: string; type: "delta"; text: string }
  | { id: string; type: "thinking"; text: string }
  | { id: string; type: "tool_exec"; callId: string; name: string; args: Record<string, unknown> }
  | { id: string; type: "assistant"; text: string; thinking?: string; toolCalls: EventToolCall[] }
  | { id: string; type: "oauth_notify"; kind: "info" | "auth_url" | "device_code" | "progress"; message?: string; url?: string; userCode?: string; verificationUri?: string }
  | { id: string; type: "oauth_prompt"; promptId: string; promptType: "text" | "secret" | "select" | "manual_code"; message: string; placeholder?: string; options?: PromptOption[] }
  | { id: string; type: "done"; stopReason: string }
  | { id: string; type: "error"; message: string };
