// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.
// Run `pnpm protocol:generate` after changing the schema.

import { z } from "zod";
import { WireMessage, WireToolDef, WordLookup, Annotation, Conversation, Collection, Item, Property, PropertyOption, Skill, SkillAdvisory, SkillBin, SkillEnv, ToolDefinition, type ProviderSummary, type EventToolCall, type PromptOption } from "./protocol.base.js";
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- refs used by generated shapes

export const PROTOCOL_VERSION = 13;

/** JSON-RPC 2.0 error codes. Below -32000 is ours; the rest is the spec's. */
export const RpcError = {
  /** Malformed JSON (spec). */
  parseError: -32700,
  /** Not a valid Request object (spec). */
  invalidRequest: -32600,
  /** Unknown method (spec). */
  methodNotFound: -32601,
  /** Params failed validation (spec). */
  invalidParams: -32602,
  /** Unhandled failure (spec). */
  internalError: -32603,
  /** Rejected credentials; offer re-authentication. */
  providerAuth: -31001,
  /** Throttled; offer retry, `data.retryAfter` when known. */
  providerRateLimit: -31002,
  /** Unreachable or failing; offer another provider. */
  providerUnavailable: -31003,
  /** Ended by $/cancelRequest. */
  cancelled: -31004,
  /** The shell could not run the tool. */
  toolFailed: -31005,
  /** No credential or model configured for the provider. */
  notConfigured: -31006,
} as const;
export type RpcErrorCode = (typeof RpcError)[keyof typeof RpcError];

// --- Params / results by method ----------------------------------------

// zod schemas exist only for messages the shell SENDS us: you validate
// what you receive, not what you produce. Server-originated messages get
// plain types, which also keeps refs like ProviderSummary type-only.

/** `ping` — Handshake. The shell refuses to proceed on a protocol mismatch. */
export const PingParams = z.object({
});
export type PingParams = z.infer<typeof PingParams>;
export type PingResult = {
  protocol: number;
  backend: string;
  /** How many catalog migrations this build knows. A backup records it so an older build can refuse a newer library outright. */
  schemaVersion: number;
};

/** `complete` — One-shot completion. Streams chat/delta, resolves when finished. */
export const CompleteParams = z.object({
  providerId: z.string(),
  model: z.string(),
  system: z.string().optional(),
  messages: z.array(WireMessage).min(1),
  maxTokens: z.number().int().positive().default(4096),
  /** Explicit key for Test Connection, before anything is saved. */
  apiKey: z.string().optional(),
  baseUrl: z.string().optional(),
});
export type CompleteParams = z.infer<typeof CompleteParams>;
export type CompleteResult = {
  stopReason: string;
};

/** `chat` — The agentic loop. Streams chat/* notifications and calls tool/execute back. */
export const ChatParams = z.object({
  providerId: z.string(),
  model: z.string(),
  system: z.string().optional(),
  messages: z.array(WireMessage).min(1),
  tools: z.array(WireToolDef).default([]),
  maxTokens: z.number().int().positive().default(8192),
  reasoning: z.enum(["minimal", "low", "medium", "high", "xhigh", "max"]).optional(),
  maxIterations: z.number().int().positive().default(10),
});
export type ChatParams = z.infer<typeof ChatParams>;
export type ChatResult = {
  stopReason: string;
};

/** `providers/list` */
export const ProvidersListParams = z.object({
});
export type ProvidersListParams = z.infer<typeof ProvidersListParams>;
export type ProvidersListResult = {
  providers: ProviderSummary[];
};

/** `credentials/set` */
export const CredentialsSetParams = z.object({
  providerId: z.string(),
  key: z.string(),
});
export type CredentialsSetParams = z.infer<typeof CredentialsSetParams>;
export type CredentialsSetResult = Record<string, never>;

/** `credentials/get` */
export const CredentialsGetParams = z.object({
  providerId: z.string(),
});
export type CredentialsGetParams = z.infer<typeof CredentialsGetParams>;
export type CredentialsGetResult = {
  /** null when the provider has no key stored. */
  apiKey?: string | null;
};

/** `credentials/delete` */
export const CredentialsDeleteParams = z.object({
  providerId: z.string(),
});
export type CredentialsDeleteParams = z.infer<typeof CredentialsDeleteParams>;
export type CredentialsDeleteResult = Record<string, never>;

/** `oauth/login` — Streams oauth/notify and calls oauth/prompt back for user input. */
export const OAuthLoginParams = z.object({
  providerId: z.string(),
});
export type OAuthLoginParams = z.infer<typeof OAuthLoginParams>;
export type OAuthLoginResult = Record<string, never>;

/** `config/setBaseUrl` */
export const ConfigSetBaseUrlParams = z.object({
  providerId: z.string(),
  /** Absent clears the override. */
  baseUrl: z.string().optional(),
});
export type ConfigSetBaseUrlParams = z.infer<typeof ConfigSetBaseUrlParams>;
export type ConfigSetBaseUrlResult = Record<string, never>;

/** `config/setLocalUrl` */
export const ConfigSetLocalUrlParams = z.object({
  providerId: z.enum(["ollama", "lmstudio"]),
  baseUrl: z.string(),
});
export type ConfigSetLocalUrlParams = z.infer<typeof ConfigSetLocalUrlParams>;
export type ConfigSetLocalUrlResult = Record<string, never>;

/** `config/modelsFile` — Where the user's models.json lives, and what went wrong reading it. */
export const ConfigModelsFileParams = z.object({
  /** Write a commented template first when the file is not there yet. */
  create: z.boolean().default(false),
});
export type ConfigModelsFileParams = z.infer<typeof ConfigModelsFileParams>;
export type ConfigModelsFileResult = {
  path: string;
  exists: boolean;
  /** Absent when the file loaded. A missing file is not an error. */
  error?: string;
};

/** `models/refresh` */
export const ModelsRefreshParams = z.object({
  providerId: z.string().optional(),
});
export type ModelsRefreshParams = z.infer<typeof ModelsRefreshParams>;
export type ModelsRefreshResult = {
  message?: string;
};

/** `catalog/annotations/list` — Live annotations on one attachment, in sort-index order. Tombstones excluded. */
export const AnnotationsListParams = z.object({
  attachmentId: z.string(),
});
export type AnnotationsListParams = z.infer<typeof AnnotationsListParams>;
export type AnnotationsListResult = {
  annotations: Annotation[];
};

/** `catalog/annotations/get` — One annotation by id, tombstoned or not. */
export const AnnotationsGetParams = z.object({
  id: z.string(),
});
export type AnnotationsGetParams = z.infer<typeof AnnotationsGetParams>;
export type AnnotationsGetResult = {
  annotation?: Annotation;
};

/** `catalog/annotations/upsert` — Insert or replace. sortIndex arrives already computed -- it encodes PDF geometry, which stays in the shell. */
export const AnnotationsUpsertParams = z.object({
  annotation: Annotation,
});
export type AnnotationsUpsertParams = z.infer<typeof AnnotationsUpsertParams>;
export type AnnotationsUpsertResult = Record<string, never>;

/** `catalog/annotations/delete` — Soft by default: the row stays as a tombstone so a later sync can tell deleted from never-existed. `hard` removes it outright. */
export const AnnotationsDeleteParams = z.object({
  id: z.string(),
  hard: z.boolean().default(false),
  /** Tombstone timestamp; required unless hard. */
  at: z.string().optional(),
});
export type AnnotationsDeleteParams = z.infer<typeof AnnotationsDeleteParams>;
export type AnnotationsDeleteResult = Record<string, never>;

/** `catalog/conversations/list` — Sessions in one scope, most recently updated first: a document's when itemId is given, a collection's when collectionId is, and the ones about neither when both are absent. Passing both is a client bug; itemId wins. */
export const ConversationsListParams = z.object({
  itemId: z.string().optional(),
  collectionId: z.string().optional(),
});
export type ConversationsListParams = z.infer<typeof ConversationsListParams>;
export type ConversationsListResult = {
  conversations: Conversation[];
};

/** `catalog/conversations/create` */
export const ConversationsCreateParams = z.object({
  conversation: Conversation,
});
export type ConversationsCreateParams = z.infer<typeof ConversationsCreateParams>;
export type ConversationsCreateResult = Record<string, never>;

/** `catalog/conversations/update` — Title and message count, as the session grows. */
export const ConversationsUpdateParams = z.object({
  id: z.string(),
  title: z.string(),
  messageCount: z.number().int().positive(),
  at: z.string(),
});
export type ConversationsUpdateParams = z.infer<typeof ConversationsUpdateParams>;
export type ConversationsUpdateResult = Record<string, never>;

/** `catalog/conversations/delete` — Removes the index row. The JSONL transcript is the shell's to delete. */
export const ConversationsDeleteParams = z.object({
  id: z.string(),
});
export type ConversationsDeleteParams = z.infer<typeof ConversationsDeleteParams>;
export type ConversationsDeleteResult = Record<string, never>;

/** `catalog/collections/list` — Every collection, ordered for display. */
export const CollectionsListParams = z.object({
});
export type CollectionsListParams = z.infer<typeof CollectionsListParams>;
export type CollectionsListResult = {
  collections: Collection[];
};

/** `catalog/collections/findBySource` — Look one up by provenance, so an import can be run twice safely. */
export const CollectionsFindBySourceParams = z.object({
  source: z.string(),
  sourceKey: z.string(),
});
export type CollectionsFindBySourceParams = z.infer<typeof CollectionsFindBySourceParams>;
export type CollectionsFindBySourceResult = {
  collection?: Collection;
};

/** `catalog/collections/upsert` */
export const CollectionsUpsertParams = z.object({
  collection: Collection,
});
export type CollectionsUpsertParams = z.infer<typeof CollectionsUpsertParams>;
export type CollectionsUpsertResult = Record<string, never>;

/** `catalog/collections/delete` — Cascades to the subtree and to memberships, never to the documents. */
export const CollectionsDeleteParams = z.object({
  id: z.string(),
});
export type CollectionsDeleteParams = z.infer<typeof CollectionsDeleteParams>;
export type CollectionsDeleteResult = Record<string, never>;

/** `catalog/collections/setMembership` — Add or remove one item. Adding twice is a no-op, not an error. */
export const CollectionsSetMembershipParams = z.object({
  itemId: z.string(),
  collectionId: z.string(),
  member: z.boolean(),
  at: z.string().optional(),
});
export type CollectionsSetMembershipParams = z.infer<typeof CollectionsSetMembershipParams>;
export type CollectionsSetMembershipResult = Record<string, never>;

/** `catalog/items/list` — The whole library as one graph: items with attachments, memberships, citations and property values. Covers are NOT included -- at ten thousand items that would pin hundreds of MB; views load them lazily by storage key. */
export const ItemsListParams = z.object({
  trashed: z.boolean().default(false),
});
export type ItemsListParams = z.infer<typeof ItemsListParams>;
export type ItemsListResult = {
  items: Item[];
};

/** `catalog/items/insert` — Item and its attachments, in one transaction. */
export const ItemsInsertParams = z.object({
  item: Item,
});
export type ItemsInsertParams = z.infer<typeof ItemsInsertParams>;
export type ItemsInsertResult = Record<string, never>;

/** `catalog/items/updateField` — One scalar field. The column set is fixed so a name cannot reach SQL from the wire. */
export const ItemsUpdateFieldParams = z.object({
  id: z.string(),
  field: z.enum(["title", "processingStatus", "lastPosition", "lastOpenedAt", "citeKey", "extra"]),
  stringValue: z.string().nullable().optional(),
  /** Used for lastPosition; the other fields travel in stringValue. */
  numberValue: z.number().nullable().optional(),
  at: z.string(),
});
export type ItemsUpdateFieldParams = z.infer<typeof ItemsUpdateFieldParams>;
export type ItemsUpdateFieldResult = Record<string, never>;

/** `catalog/items/setTrashed` — Move to or out of the trash. The rows stay either way. */
export const ItemsSetTrashedParams = z.object({
  ids: z.array(z.string()),
  trashed: z.boolean(),
  at: z.string(),
});
export type ItemsSetTrashedParams = z.infer<typeof ItemsSetTrashedParams>;
export type ItemsSetTrashedResult = Record<string, never>;

/** `catalog/items/remove` — Permanent. Cascades to attachments, annotations, memberships and citations. */
export const ItemsRemoveParams = z.object({
  ids: z.array(z.string()),
});
export type ItemsRemoveParams = z.infer<typeof ItemsRemoveParams>;
export type ItemsRemoveResult = Record<string, never>;

/** `catalog/items/merge` — Fold duplicates into a keeper: re-parent everything they own, then delete them. Rows only — the files on disk are the shell's to move. */
export const ItemsMergeParams = z.object({
  keeperId: z.string(),
  duplicateIds: z.array(z.string()),
  at: z.string(),
});
export type ItemsMergeParams = z.infer<typeof ItemsMergeParams>;
export type ItemsMergeResult = Record<string, never>;

/** `catalog/validate` — Can this database file be opened by the build that owns the schema? Used before a restore swaps a backup in, while nothing live has been touched, so an incompatible one is a refusal rather than a crash. */
export const CatalogValidateParams = z.object({
  path: z.string(),
});
export type CatalogValidateParams = z.infer<typeof CatalogValidateParams>;
export type CatalogValidateResult = {
  ok: boolean;
  error?: string | null;
};

/** `catalog/references/get` — An item's CSL JSON, or null when it has no citation. */
export const ReferencesGetParams = z.object({
  itemId: z.string(),
});
export type ReferencesGetParams = z.infer<typeof ReferencesGetParams>;
export type ReferencesGetResult = {
  cslJson?: string | null;
};

/** `catalog/references/save` — Save an item's metadata: the citation, the columns derived from it, the item's own author and title, and a cite key if it had none. */
export const ReferencesSaveParams = z.object({
  itemId: z.string(),
  cslJson: z.string(),
  extra: z.string().nullable().optional(),
  at: z.string(),
});
export type ReferencesSaveParams = z.infer<typeof ReferencesSaveParams>;
export type ReferencesSaveResult = Record<string, never>;

/** `metadata/recognize` — Work out what a document is: read its embedded metadata and the identifiers printed on it, resolve those against CrossRef, DataCite, arXiv, Open Library, Google Books or PubMed, and fall back to a title search when it carries no identifier at all. Returns CSL JSON with the method and confidence that produced it. */
export const MetadataRecognizeParams = z.object({
  /** The document to read. Omit to recognise from title and author alone. */
  filePath: z.string().nullable().optional(),
  fileName: z.string().nullable().optional(),
  /** What the catalog already believes, used when the file says nothing. */
  title: z.string().nullable().optional(),
  author: z.string().nullable().optional(),
  /** Resolve this identifier instead of reading the file. A DOI, an arXiv id, an ISBN or a PMID -- the kind is worked out from its shape. */
  identifier: z.string().nullable().optional(),
  /** Skip every lookup; read the file's own metadata only. */
  offline: z.boolean().optional(),
});
export type MetadataRecognizeParams = z.infer<typeof MetadataRecognizeParams>;
export type MetadataRecognizeResult = {
  cslJson: string;
  method: "doi" | "arxiv" | "isbn" | "pmid" | "title-search" | "embedded" | "filename";
  /** 0-1. Below 0.5 this is a description of the file, not an identification. */
  confidence: number;
  provider?: string | null;
  doi?: string | null;
  arxiv?: string | null;
  isbn?: string | null;
  pmid?: string | null;
  /** Every step tried, in order, so a wrong answer can be explained. */
  trail: string[];
};

/** `catalog/citeKeys/propose` — The key this item's current metadata would produce, without writing it. Null when there is not enough metadata to form one. */
export const CiteKeysProposeParams = z.object({
  itemId: z.string(),
});
export type CiteKeysProposeParams = z.infer<typeof CiteKeysProposeParams>;
export type CiteKeysProposeResult = {
  key?: string | null;
};

/** `catalog/citeKeys/assign` — Give an item a cite key unless it already has one. Returns the key it settled on, or null when the metadata cannot form one. */
export const CiteKeysAssignParams = z.object({
  itemId: z.string(),
  at: z.string(),
});
export type CiteKeysAssignParams = z.infer<typeof CiteKeysAssignParams>;
export type CiteKeysAssignResult = {
  key?: string | null;
};

/** `catalog/citeKeys/save` — Save a key the user typed. Fails if another item already uses it. */
export const CiteKeysSaveParams = z.object({
  key: z.string(),
  itemId: z.string(),
  at: z.string(),
});
export type CiteKeysSaveParams = z.infer<typeof CiteKeysSaveParams>;
export type CiteKeysSaveResult = Record<string, never>;

/** `catalog/properties/list` — Every property with its options, both in display order. */
export const PropertiesListParams = z.object({
});
export type PropertiesListParams = z.infer<typeof PropertiesListParams>;
export type PropertiesListResult = {
  properties: Property[];
};

/** `catalog/properties/upsertOption` */
export const PropertiesUpsertOptionParams = z.object({
  option: PropertyOption,
});
export type PropertiesUpsertOptionParams = z.infer<typeof PropertiesUpsertOptionParams>;
export type PropertiesUpsertOptionResult = Record<string, never>;

/** `catalog/properties/deleteOption` — Cascades to every item value that pointed at it. */
export const PropertiesDeleteOptionParams = z.object({
  id: z.string(),
});
export type PropertiesDeleteOptionParams = z.infer<typeof PropertiesDeleteOptionParams>;
export type PropertiesDeleteOptionResult = Record<string, never>;

/** `catalog/properties/addSelectValue` — Add a chosen option. Replaces the previous value for a single-select property and appends for a multi-select; the core reads the type. */
export const PropertiesAddSelectValueParams = z.object({
  valueId: z.string(),
  itemId: z.string(),
  propertyId: z.string(),
  optionId: z.string(),
});
export type PropertiesAddSelectValueParams = z.infer<typeof PropertiesAddSelectValueParams>;
export type PropertiesAddSelectValueResult = Record<string, never>;

/** `catalog/properties/removeSelectValue` — Remove one chosen option, leaving the item's other values alone. */
export const PropertiesRemoveSelectValueParams = z.object({
  itemId: z.string(),
  propertyId: z.string(),
  optionId: z.string(),
});
export type PropertiesRemoveSelectValueParams = z.infer<typeof PropertiesRemoveSelectValueParams>;
export type PropertiesRemoveSelectValueResult = Record<string, never>;

/** `prompts/compose` — The static half of the system prompt: base.md, the named mixins, and the skills listing. The shell appends live context afterwards -- that half cannot be a file. */
export const PromptsComposeParams = z.object({
  /** Mixin names, without .md, in the order they should appear. */
  mixins: z.array(z.string()).default([]),
  /** Whether the model has a read tool. The skills listing tells it to read a skill's file, so without one the listing is omitted. */
  hasReadTool: z.boolean().default(false),
});
export type PromptsComposeParams = z.infer<typeof PromptsComposeParams>;
export type PromptsComposeResult = {
  /** Empty when no prompt files were found. */
  text: string;
  /** Mixins that existed and were included. */
  used: string[];
  /** Every mixin this build carries. */
  available: string[];
};

/** `skills/list` — Every skill the core can see, bundled and installed. The listing the model gets is composed here too -- see prompts/compose. */
export const SkillsListParams = z.object({
});
export type SkillsListParams = z.infer<typeof SkillsListParams>;
export type SkillsListResult = {
  skills: Skill[];
  /** Malformed or duplicate skills, so one can be fixed rather than vanish. */
  advisories: SkillAdvisory[];
};

/** `tools/list` — The tools the core implements: the ones that touch this machine rather than the app. The shell declares them to the model alongside its own and gates them the same way. */
export const ToolsListParams = z.object({
});
export type ToolsListParams = z.infer<typeof ToolsListParams>;
export type ToolsListResult = {
  tools: ToolDefinition[];
};

/** `tools/run` — Run one of them. Called by the shell AFTER it has shown the call and taken the user's decision -- the side that approves is the side that runs, which is one fewer way for an unapproved command to happen. */
export const ToolsRunParams = z.object({
  name: z.string(),
  /** The model's arguments, as strings. */
  args: z.record(z.string(), z.any()),
  workingDirectory: z.string(),
  /** Roots a path must sit inside. Empty means unsandboxed. */
  allowedPaths: z.array(z.string()).default([]),
});
export type ToolsRunParams = z.infer<typeof ToolsRunParams>;
export type ToolsRunResult = {
  content: string;
  isError: boolean;
};

/** `skills/body` — One skill's SKILL.md body, without its frontmatter. Read on demand rather than listed: the bodies are long prose, and only the active skill's is ever used. The shell places it after the live context, which is why it is not part of prompts/compose. */
export const SkillsBodyParams = z.object({
  name: z.string(),
});
export type SkillsBodyParams = z.infer<typeof SkillsBodyParams>;
export type SkillsBodyResult = {
  /** Empty when there is no such skill. */
  body: string;
};

/** `catalog/wordLookups/list` — One document's lookups, or every one when itemId is absent. Newest first. */
export const WordLookupsListParams = z.object({
  itemId: z.string().optional(),
});
export type WordLookupsListParams = z.infer<typeof WordLookupsListParams>;
export type WordLookupsListResult = {
  lookups: WordLookup[];
};

/** `catalog/wordLookups/save` — Insert, replacing any prior lookup of the same word in the same document. */
export const WordLookupsSaveParams = z.object({
  lookup: WordLookup,
});
export type WordLookupsSaveParams = z.infer<typeof WordLookupsSaveParams>;
export type WordLookupsSaveResult = Record<string, never>;

/** `catalog/wordLookups/delete` */
export const WordLookupsDeleteParams = z.object({
  id: z.string(),
});
export type WordLookupsDeleteParams = z.infer<typeof WordLookupsDeleteParams>;
export type WordLookupsDeleteResult = Record<string, never>;

/** `catalog/wordLookups/clear` — Clear one document's history, or all of it when itemId is absent. */
export const WordLookupsClearParams = z.object({
  itemId: z.string().optional(),
});
export type WordLookupsClearParams = z.infer<typeof WordLookupsClearParams>;
export type WordLookupsClearResult = Record<string, never>;

/** `$/cancelRequest` — LSP's spelling. The peer fails the named request and anything it spawned. */
export const CancelRequestParams = z.object({
  id: z.string(),
});
export type CancelRequestParams = z.infer<typeof CancelRequestParams>;

/** `tool/execute` — The shell runs the tool and answers. Tools read local app state, so they cannot run in the sidecar. */
export type ToolExecuteParams = {
  /** Id of the request this belongs to. */
  token: string;
  name: string;
  args: Record<string, unknown>;
};
export type ToolExecuteResult = {
  content: string;
  isError: boolean;
};

/** `oauth/prompt` — Asks the shell for one piece of user input during a login. */
export type OAuthPromptParams = {
  /** Id of the request this belongs to. */
  token: string;
  promptType: "text" | "secret" | "select" | "manual_code";
  message: string;
  placeholder?: string;
  options?: PromptOption[];
};
export type OAuthPromptResult = {
  /** Absent means cancelled. */
  value?: string;
};

/** `chat/delta` */
export type ChatDeltaParams = {
  /** Id of the request this belongs to. */
  token: string;
  text: string;
};

/** `chat/thinking` */
export type ChatThinkingParams = {
  /** Id of the request this belongs to. */
  token: string;
  text: string;
};

/** `chat/assistant` — Authoritative snapshot of one iteration's assistant message. */
export type ChatAssistantParams = {
  /** Id of the request this belongs to. */
  token: string;
  text: string;
  thinking?: string;
  toolCalls: EventToolCall[];
};

/** `oauth/notify` */
export type OAuthNotifyParams = {
  /** Id of the request this belongs to. */
  token: string;
  kind: "info" | "auth_url" | "device_code" | "progress";
  message?: string;
  url?: string;
  userCode?: string;
  verificationUri?: string;
};

// --- Dispatch tables ---------------------------------------------------

/** Requests the shell sends us, by method name. */
export const ClientRequests = {
  "ping": PingParams,
  "complete": CompleteParams,
  "chat": ChatParams,
  "providers/list": ProvidersListParams,
  "credentials/set": CredentialsSetParams,
  "credentials/get": CredentialsGetParams,
  "credentials/delete": CredentialsDeleteParams,
  "oauth/login": OAuthLoginParams,
  "config/setBaseUrl": ConfigSetBaseUrlParams,
  "config/setLocalUrl": ConfigSetLocalUrlParams,
  "config/modelsFile": ConfigModelsFileParams,
  "models/refresh": ModelsRefreshParams,
  "catalog/annotations/list": AnnotationsListParams,
  "catalog/annotations/get": AnnotationsGetParams,
  "catalog/annotations/upsert": AnnotationsUpsertParams,
  "catalog/annotations/delete": AnnotationsDeleteParams,
  "catalog/conversations/list": ConversationsListParams,
  "catalog/conversations/create": ConversationsCreateParams,
  "catalog/conversations/update": ConversationsUpdateParams,
  "catalog/conversations/delete": ConversationsDeleteParams,
  "catalog/collections/list": CollectionsListParams,
  "catalog/collections/findBySource": CollectionsFindBySourceParams,
  "catalog/collections/upsert": CollectionsUpsertParams,
  "catalog/collections/delete": CollectionsDeleteParams,
  "catalog/collections/setMembership": CollectionsSetMembershipParams,
  "catalog/items/list": ItemsListParams,
  "catalog/items/insert": ItemsInsertParams,
  "catalog/items/updateField": ItemsUpdateFieldParams,
  "catalog/items/setTrashed": ItemsSetTrashedParams,
  "catalog/items/remove": ItemsRemoveParams,
  "catalog/items/merge": ItemsMergeParams,
  "catalog/validate": CatalogValidateParams,
  "catalog/references/get": ReferencesGetParams,
  "catalog/references/save": ReferencesSaveParams,
  "metadata/recognize": MetadataRecognizeParams,
  "catalog/citeKeys/propose": CiteKeysProposeParams,
  "catalog/citeKeys/assign": CiteKeysAssignParams,
  "catalog/citeKeys/save": CiteKeysSaveParams,
  "catalog/properties/list": PropertiesListParams,
  "catalog/properties/upsertOption": PropertiesUpsertOptionParams,
  "catalog/properties/deleteOption": PropertiesDeleteOptionParams,
  "catalog/properties/addSelectValue": PropertiesAddSelectValueParams,
  "catalog/properties/removeSelectValue": PropertiesRemoveSelectValueParams,
  "prompts/compose": PromptsComposeParams,
  "skills/list": SkillsListParams,
  "tools/list": ToolsListParams,
  "tools/run": ToolsRunParams,
  "skills/body": SkillsBodyParams,
  "catalog/wordLookups/list": WordLookupsListParams,
  "catalog/wordLookups/save": WordLookupsSaveParams,
  "catalog/wordLookups/delete": WordLookupsDeleteParams,
  "catalog/wordLookups/clear": WordLookupsClearParams,
} as const;

/** Notifications the shell sends us. */
export const ClientNotifications = {
  "$/cancelRequest": CancelRequestParams,
} as const;

export type ClientRequestMethod = keyof typeof ClientRequests;
export type ClientNotificationMethod = keyof typeof ClientNotifications;
/** Maps each client request method to its result type. */
export interface ClientRequestResults {
  "ping": PingResult;
  "complete": CompleteResult;
  "chat": ChatResult;
  "providers/list": ProvidersListResult;
  "credentials/set": CredentialsSetResult;
  "credentials/get": CredentialsGetResult;
  "credentials/delete": CredentialsDeleteResult;
  "oauth/login": OAuthLoginResult;
  "config/setBaseUrl": ConfigSetBaseUrlResult;
  "config/setLocalUrl": ConfigSetLocalUrlResult;
  "config/modelsFile": ConfigModelsFileResult;
  "models/refresh": ModelsRefreshResult;
  "catalog/annotations/list": AnnotationsListResult;
  "catalog/annotations/get": AnnotationsGetResult;
  "catalog/annotations/upsert": AnnotationsUpsertResult;
  "catalog/annotations/delete": AnnotationsDeleteResult;
  "catalog/conversations/list": ConversationsListResult;
  "catalog/conversations/create": ConversationsCreateResult;
  "catalog/conversations/update": ConversationsUpdateResult;
  "catalog/conversations/delete": ConversationsDeleteResult;
  "catalog/collections/list": CollectionsListResult;
  "catalog/collections/findBySource": CollectionsFindBySourceResult;
  "catalog/collections/upsert": CollectionsUpsertResult;
  "catalog/collections/delete": CollectionsDeleteResult;
  "catalog/collections/setMembership": CollectionsSetMembershipResult;
  "catalog/items/list": ItemsListResult;
  "catalog/items/insert": ItemsInsertResult;
  "catalog/items/updateField": ItemsUpdateFieldResult;
  "catalog/items/setTrashed": ItemsSetTrashedResult;
  "catalog/items/remove": ItemsRemoveResult;
  "catalog/items/merge": ItemsMergeResult;
  "catalog/validate": CatalogValidateResult;
  "catalog/references/get": ReferencesGetResult;
  "catalog/references/save": ReferencesSaveResult;
  "metadata/recognize": MetadataRecognizeResult;
  "catalog/citeKeys/propose": CiteKeysProposeResult;
  "catalog/citeKeys/assign": CiteKeysAssignResult;
  "catalog/citeKeys/save": CiteKeysSaveResult;
  "catalog/properties/list": PropertiesListResult;
  "catalog/properties/upsertOption": PropertiesUpsertOptionResult;
  "catalog/properties/deleteOption": PropertiesDeleteOptionResult;
  "catalog/properties/addSelectValue": PropertiesAddSelectValueResult;
  "catalog/properties/removeSelectValue": PropertiesRemoveSelectValueResult;
  "prompts/compose": PromptsComposeResult;
  "skills/list": SkillsListResult;
  "tools/list": ToolsListResult;
  "tools/run": ToolsRunResult;
  "skills/body": SkillsBodyResult;
  "catalog/wordLookups/list": WordLookupsListResult;
  "catalog/wordLookups/save": WordLookupsSaveResult;
  "catalog/wordLookups/delete": WordLookupsDeleteResult;
  "catalog/wordLookups/clear": WordLookupsClearResult;
}

/** Requests we send to the shell. */
export type ServerRequestMethod =
  | "tool/execute"
  | "oauth/prompt"
  ;

/** Notifications we send to the shell. */
export type ServerNotificationMethod =
  | "chat/delta"
  | "chat/thinking"
  | "chat/assistant"
  | "oauth/notify"
  ;
