// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.
// Run `pnpm protocol:generate` after changing the schema.

import Foundation

/// The sidecar protocol: JSON-RPC 2.0 over newline-delimited stdio.
///
/// Per-method params and results, rather than one flat struct of optionals.
/// Reverse calls (tool/execute, oauth/prompt) are ordinary requests in the
/// other direction, so they need no separate machinery.
enum RPC {
    static let version = 10

    /// JSON-RPC error codes. The shell branches on these: re-authenticate
    /// is a different affordance from retry, and the old single error string
    /// could not distinguish them.
    enum ErrorCode {
        /// Malformed JSON (spec).
        static let parseError = -32700
        /// Not a valid Request object (spec).
        static let invalidRequest = -32600
        /// Unknown method (spec).
        static let methodNotFound = -32601
        /// Params failed validation (spec).
        static let invalidParams = -32602
        /// Unhandled failure (spec).
        static let internalError = -32603
        /// Rejected credentials; offer re-authentication.
        static let providerAuth = -31001
        /// Throttled; offer retry, `data.retryAfter` when known.
        static let providerRateLimit = -31002
        /// Unreachable or failing; offer another provider.
        static let providerUnavailable = -31003
        /// Ended by $/cancelRequest.
        static let cancelled = -31004
        /// The shell could not run the tool.
        static let toolFailed = -31005
        /// No credential or model configured for the provider.
        static let notConfigured = -31006
    }

    /// Method names, so call sites never spell one by hand.
    enum Method {
        static let ping = "ping"
        static let complete = "complete"
        static let chat = "chat"
        static let providersList = "providers/list"
        static let credentialsSet = "credentials/set"
        static let credentialsGet = "credentials/get"
        static let credentialsDelete = "credentials/delete"
        static let oAuthLogin = "oauth/login"
        static let configSetBaseUrl = "config/setBaseUrl"
        static let configSetLocalUrl = "config/setLocalUrl"
        static let modelsRefresh = "models/refresh"
        static let annotationsList = "catalog/annotations/list"
        static let annotationsGet = "catalog/annotations/get"
        static let annotationsUpsert = "catalog/annotations/upsert"
        static let annotationsDelete = "catalog/annotations/delete"
        static let conversationsList = "catalog/conversations/list"
        static let conversationsCreate = "catalog/conversations/create"
        static let conversationsUpdate = "catalog/conversations/update"
        static let conversationsDelete = "catalog/conversations/delete"
        static let collectionsList = "catalog/collections/list"
        static let collectionsFindBySource = "catalog/collections/findBySource"
        static let collectionsUpsert = "catalog/collections/upsert"
        static let collectionsDelete = "catalog/collections/delete"
        static let collectionsSetMembership = "catalog/collections/setMembership"
        static let collectionsItems = "catalog/collections/items"
        static let itemsList = "catalog/items/list"
        static let itemsFind = "catalog/items/find"
        static let itemsInsert = "catalog/items/insert"
        static let itemsUpdateField = "catalog/items/updateField"
        static let itemsSetTrashed = "catalog/items/setTrashed"
        static let itemsRemove = "catalog/items/remove"
        static let itemsMerge = "catalog/items/merge"
        static let propertiesList = "catalog/properties/list"
        static let propertiesUpsert = "catalog/properties/upsert"
        static let propertiesDelete = "catalog/properties/delete"
        static let propertiesUpsertOption = "catalog/properties/upsertOption"
        static let propertiesDeleteOption = "catalog/properties/deleteOption"
        static let propertiesAddSelectValue = "catalog/properties/addSelectValue"
        static let propertiesRemoveSelectValue = "catalog/properties/removeSelectValue"
        static let propertiesSetTextValue = "catalog/properties/setTextValue"
        static let promptsCompose = "prompts/compose"
        static let wordLookupsList = "catalog/wordLookups/list"
        static let wordLookupsSave = "catalog/wordLookups/save"
        static let wordLookupsDelete = "catalog/wordLookups/delete"
        static let wordLookupsClear = "catalog/wordLookups/clear"
        static let cancelRequest = "$/cancelRequest"
        static let toolExecute = "tool/execute"
        static let oAuthPrompt = "oauth/prompt"
        static let chatDelta = "chat/delta"
        static let chatThinking = "chat/thinking"
        static let chatAssistant = "chat/assistant"
        static let oAuthNotify = "oauth/notify"
    }

    // MARK: ping
    /// Handshake. The shell refuses to proceed on a protocol mismatch.
    struct PingParams: Encodable {
        init() {}
    }
    struct PingResult: Decodable {
        var `protocol`: Int
        var backend: String
    }

    // MARK: complete
    /// One-shot completion. Streams chat/delta, resolves when finished.
    struct CompleteParams: Encodable {
        var providerId: String
        var model: String
        var system: String?
        var messages: [WireMessage]
        var maxTokens: Int?
        /// Explicit key for Test Connection, before anything is saved.
        var apiKey: String?
        var baseUrl: String?
    }
    struct CompleteResult: Decodable {
        var stopReason: String
    }

    // MARK: chat
    /// The agentic loop. Streams chat/* notifications and calls tool/execute back.
    struct ChatParams: Encodable {
        var providerId: String
        var model: String
        var system: String?
        var messages: [WireMessage]
        var tools: [WireToolDef]?
        var maxTokens: Int?
        var reasoning: String?
        var maxIterations: Int?
    }
    struct ChatResult: Decodable {
        var stopReason: String
    }

    // MARK: providers/list
    struct ProvidersListParams: Encodable {
        init() {}
    }
    struct ProvidersListResult: Decodable {
        var providers: [BackendProviderSummary]
    }

    // MARK: credentials/set
    struct CredentialsSetParams: Encodable {
        var providerId: String
        var key: String
    }
    struct CredentialsSetResult: Decodable {
        init() {}
    }

    // MARK: credentials/get
    struct CredentialsGetParams: Encodable {
        var providerId: String
    }
    struct CredentialsGetResult: Decodable {
        /// null when the provider has no key stored.
        var apiKey: String?
    }

    // MARK: credentials/delete
    struct CredentialsDeleteParams: Encodable {
        var providerId: String
    }
    struct CredentialsDeleteResult: Decodable {
        init() {}
    }

    // MARK: oauth/login
    /// Streams oauth/notify and calls oauth/prompt back for user input.
    struct OAuthLoginParams: Encodable {
        var providerId: String
    }
    struct OAuthLoginResult: Decodable {
        init() {}
    }

    // MARK: config/setBaseUrl
    struct ConfigSetBaseUrlParams: Encodable {
        var providerId: String
        /// Absent clears the override.
        var baseUrl: String?
    }
    struct ConfigSetBaseUrlResult: Decodable {
        init() {}
    }

    // MARK: config/setLocalUrl
    struct ConfigSetLocalUrlParams: Encodable {
        var providerId: String
        var baseUrl: String
    }
    struct ConfigSetLocalUrlResult: Decodable {
        init() {}
    }

    // MARK: models/refresh
    struct ModelsRefreshParams: Encodable {
        var providerId: String?
    }
    struct ModelsRefreshResult: Decodable {
        var message: String?
    }

    // MARK: catalog/annotations/list
    /// Live annotations on one attachment, in sort-index order. Tombstones excluded.
    struct AnnotationsListParams: Encodable {
        var attachmentId: String
    }
    struct AnnotationsListResult: Decodable {
        var annotations: [CatalogAnnotation]
    }

    // MARK: catalog/annotations/get
    /// One annotation by id, tombstoned or not.
    struct AnnotationsGetParams: Encodable {
        var `id`: String
    }
    struct AnnotationsGetResult: Decodable {
        var annotation: CatalogAnnotation?
    }

    // MARK: catalog/annotations/upsert
    /// Insert or replace. sortIndex arrives already computed -- it encodes PDF geometry, which
    /// stays in the shell.
    struct AnnotationsUpsertParams: Encodable {
        var annotation: CatalogAnnotation
    }
    struct AnnotationsUpsertResult: Decodable {
        init() {}
    }

    // MARK: catalog/annotations/delete
    /// Soft by default: the row stays as a tombstone so a later sync can tell deleted from
    /// never-existed. `hard` removes it outright.
    struct AnnotationsDeleteParams: Encodable {
        var `id`: String
        var hard: Bool?
        /// Tombstone timestamp; required unless hard.
        var at: String?
    }
    struct AnnotationsDeleteResult: Decodable {
        init() {}
    }

    // MARK: catalog/conversations/list
    /// Sessions for one document, or the library-wide ones when itemId is absent. Most recently
    /// updated first.
    struct ConversationsListParams: Encodable {
        var itemId: String?
    }
    struct ConversationsListResult: Decodable {
        var conversations: [CatalogConversation]
    }

    // MARK: catalog/conversations/create
    struct ConversationsCreateParams: Encodable {
        var conversation: CatalogConversation
    }
    struct ConversationsCreateResult: Decodable {
        init() {}
    }

    // MARK: catalog/conversations/update
    /// Title and message count, as the session grows.
    struct ConversationsUpdateParams: Encodable {
        var `id`: String
        var title: String
        var messageCount: Int
        var at: String
    }
    struct ConversationsUpdateResult: Decodable {
        init() {}
    }

    // MARK: catalog/conversations/delete
    /// Removes the index row. The JSONL transcript is the shell's to delete.
    struct ConversationsDeleteParams: Encodable {
        var `id`: String
    }
    struct ConversationsDeleteResult: Decodable {
        init() {}
    }

    // MARK: catalog/collections/list
    /// Every collection, ordered for display.
    struct CollectionsListParams: Encodable {
        init() {}
    }
    struct CollectionsListResult: Decodable {
        var collections: [CatalogCollection]
    }

    // MARK: catalog/collections/findBySource
    /// Look one up by provenance, so an import can be run twice safely.
    struct CollectionsFindBySourceParams: Encodable {
        var source: String
        var sourceKey: String
    }
    struct CollectionsFindBySourceResult: Decodable {
        var collection: CatalogCollection?
    }

    // MARK: catalog/collections/upsert
    struct CollectionsUpsertParams: Encodable {
        var collection: CatalogCollection
    }
    struct CollectionsUpsertResult: Decodable {
        init() {}
    }

    // MARK: catalog/collections/delete
    /// Cascades to the subtree and to memberships, never to the documents.
    struct CollectionsDeleteParams: Encodable {
        var `id`: String
    }
    struct CollectionsDeleteResult: Decodable {
        init() {}
    }

    // MARK: catalog/collections/setMembership
    /// Add or remove one item. Adding twice is a no-op, not an error.
    struct CollectionsSetMembershipParams: Encodable {
        var itemId: String
        var collectionId: String
        var member: Bool
        var at: String?
    }
    struct CollectionsSetMembershipResult: Decodable {
        init() {}
    }

    // MARK: catalog/collections/items
    /// Item ids in a plain collection. A smart one is a query, not a list.
    struct CollectionsItemsParams: Encodable {
        var collectionId: String
    }
    struct CollectionsItemsResult: Decodable {
        var itemIds: [String]
        var count: Int
    }

    // MARK: catalog/items/list
    /// The whole library as one graph: items with attachments, memberships, citations and property
    /// values. Covers are NOT included -- at ten thousand items that would pin hundreds of MB;
    /// views load them lazily by storage key.
    struct ItemsListParams: Encodable {
        var trashed: Bool?
    }
    struct ItemsListResult: Decodable {
        var items: [CatalogItem]
    }

    // MARK: catalog/items/find
    /// One item by a unique handle. `source` needs `sourceKey` too.
    struct ItemsFindParams: Encodable {
        var by: String
        var value: String
        var sourceKey: String?
    }
    struct ItemsFindResult: Decodable {
        var item: CatalogItem?
    }

    // MARK: catalog/items/insert
    /// Item and its attachments, in one transaction.
    struct ItemsInsertParams: Encodable {
        var item: CatalogItem
    }
    struct ItemsInsertResult: Decodable {
        init() {}
    }

    // MARK: catalog/items/updateField
    /// One scalar field. The column set is fixed so a name cannot reach SQL from the wire.
    struct ItemsUpdateFieldParams: Encodable {
        var `id`: String
        var field: String
        var stringValue: String?
        /// Used for lastPosition; the other fields travel in stringValue.
        var numberValue: Double?
        var at: String
    }
    struct ItemsUpdateFieldResult: Decodable {
        init() {}
    }

    // MARK: catalog/items/setTrashed
    /// Move to or out of the trash. The rows stay either way.
    struct ItemsSetTrashedParams: Encodable {
        var ids: [String]
        var trashed: Bool
        var at: String
    }
    struct ItemsSetTrashedResult: Decodable {
        init() {}
    }

    // MARK: catalog/items/remove
    /// Permanent. Cascades to attachments, annotations, memberships and citations.
    struct ItemsRemoveParams: Encodable {
        var ids: [String]
    }
    struct ItemsRemoveResult: Decodable {
        init() {}
    }

    // MARK: catalog/items/merge
    /// Fold duplicates into a keeper: re-parent everything they own, then delete them. Rows only —
    /// the files on disk are the shell's to move.
    struct ItemsMergeParams: Encodable {
        var keeperId: String
        var duplicateIds: [String]
        var at: String
    }
    struct ItemsMergeResult: Decodable {
        init() {}
    }

    // MARK: catalog/properties/list
    /// Every property with its options, both in display order.
    struct PropertiesListParams: Encodable {
        init() {}
    }
    struct PropertiesListResult: Decodable {
        var properties: [CatalogProperty]
    }

    // MARK: catalog/properties/upsert
    struct PropertiesUpsertParams: Encodable {
        var property: CatalogProperty
    }
    struct PropertiesUpsertResult: Decodable {
        init() {}
    }

    // MARK: catalog/properties/delete
    /// Cascades to the property's options and every value using them.
    struct PropertiesDeleteParams: Encodable {
        var `id`: String
    }
    struct PropertiesDeleteResult: Decodable {
        init() {}
    }

    // MARK: catalog/properties/upsertOption
    struct PropertiesUpsertOptionParams: Encodable {
        var option: CatalogPropertyOption
    }
    struct PropertiesUpsertOptionResult: Decodable {
        init() {}
    }

    // MARK: catalog/properties/deleteOption
    /// Cascades to every item value that pointed at it.
    struct PropertiesDeleteOptionParams: Encodable {
        var `id`: String
    }
    struct PropertiesDeleteOptionResult: Decodable {
        init() {}
    }

    // MARK: catalog/properties/addSelectValue
    /// Add a chosen option. Replaces the previous value for a single-select property and appends
    /// for a multi-select; the core reads the type.
    struct PropertiesAddSelectValueParams: Encodable {
        var valueId: String
        var itemId: String
        var propertyId: String
        var optionId: String
    }
    struct PropertiesAddSelectValueResult: Decodable {
        init() {}
    }

    // MARK: catalog/properties/removeSelectValue
    /// Remove one chosen option, leaving the item's other values alone.
    struct PropertiesRemoveSelectValueParams: Encodable {
        var itemId: String
        var propertyId: String
        var optionId: String
    }
    struct PropertiesRemoveSelectValueResult: Decodable {
        init() {}
    }

    // MARK: catalog/properties/setTextValue
    /// Set a text or number value, replacing any previous one. Empty clears it.
    struct PropertiesSetTextValueParams: Encodable {
        var valueId: String
        var itemId: String
        var propertyId: String
        var value: String
    }
    struct PropertiesSetTextValueResult: Decodable {
        init() {}
    }

    // MARK: prompts/compose
    /// The static half of the system prompt: base.md plus the named mixins. The shell appends live
    /// context afterwards -- that half cannot be a file.
    struct PromptsComposeParams: Encodable {
        /// Mixin names, without .md, in the order they should appear.
        var mixins: [String]?
    }
    struct PromptsComposeResult: Decodable {
        /// Empty when no prompt files were found.
        var text: String
        /// Mixins that existed and were included.
        var used: [String]
        /// Every mixin this build carries.
        var available: [String]
    }

    // MARK: catalog/wordLookups/list
    /// One document's lookups, or every one when itemId is absent. Newest first.
    struct WordLookupsListParams: Encodable {
        var itemId: String?
    }
    struct WordLookupsListResult: Decodable {
        var lookups: [CatalogWordLookup]
    }

    // MARK: catalog/wordLookups/save
    /// Insert, replacing any prior lookup of the same word in the same document.
    struct WordLookupsSaveParams: Encodable {
        var lookup: CatalogWordLookup
    }
    struct WordLookupsSaveResult: Decodable {
        init() {}
    }

    // MARK: catalog/wordLookups/delete
    struct WordLookupsDeleteParams: Encodable {
        var `id`: String
    }
    struct WordLookupsDeleteResult: Decodable {
        init() {}
    }

    // MARK: catalog/wordLookups/clear
    /// Clear one document's history, or all of it when itemId is absent.
    struct WordLookupsClearParams: Encodable {
        var itemId: String?
    }
    struct WordLookupsClearResult: Decodable {
        init() {}
    }

    // MARK: $/cancelRequest
    /// LSP's spelling. The peer fails the named request and anything it spawned.
    struct CancelRequestParams: Encodable {
        var `id`: String
    }

    // MARK: tool/execute
    /// The shell runs the tool and answers. Tools read local app state, so they cannot run in the
    /// sidecar.
    struct ToolExecuteParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var name: String
        var args: [String: JSONFragment]
    }
    struct ToolExecuteResult: Encodable {
        var content: String
        var isError: Bool?
    }

    // MARK: oauth/prompt
    /// Asks the shell for one piece of user input during a login.
    struct OAuthPromptParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var promptType: String
        var message: String
        var placeholder: String?
        var options: [BackendPromptOption]?
    }
    struct OAuthPromptResult: Encodable {
        /// Absent means cancelled.
        var value: String?
    }

    // MARK: chat/delta
    struct ChatDeltaParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var text: String
    }

    // MARK: chat/thinking
    struct ChatThinkingParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var text: String
    }

    // MARK: chat/assistant
    /// Authoritative snapshot of one iteration's assistant message.
    struct ChatAssistantParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var text: String
        var thinking: String?
        var toolCalls: [BackendToolCall]
    }

    // MARK: oauth/notify
    struct OAuthNotifyParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var kind: String
        var message: String?
        var url: String?
        var userCode: String?
        var verificationUri: String?
    }

}
