// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.
// Run `pnpm protocol:generate` after changing the schema.

import Foundation

/// The sidecar protocol: JSON-RPC 2.0 over newline-delimited stdio.
///
/// Per-method params and results, rather than one flat struct of optionals.
/// Reverse calls (tool/execute, oauth/prompt) are ordinary requests in the
/// other direction, so they need no separate machinery.
enum RPC {
    static let version = 5

    /// JSON-RPC error codes. The shell branches on these: re-authenticate
    /// is a different affordance from retry, and the old single error string
    /// could not distinguish them.
    enum ErrorCode {
        /// Malformed JSON (spec).
        static let parseError = -32700
        /// Not a valid Request object (spec).
        static let invalidRequest = -32600
        /// Unknown method (spec).
        static let methodNotFound = -32601
        /// Params failed validation (spec).
        static let invalidParams = -32602
        /// Unhandled failure (spec).
        static let internalError = -32603
        /// Rejected credentials; offer re-authentication.
        static let providerAuth = -31001
        /// Throttled; offer retry, `data.retryAfter` when known.
        static let providerRateLimit = -31002
        /// Unreachable or failing; offer another provider.
        static let providerUnavailable = -31003
        /// Ended by $/cancelRequest.
        static let cancelled = -31004
        /// The shell could not run the tool.
        static let toolFailed = -31005
        /// No credential or model configured for the provider.
        static let notConfigured = -31006
    }

    /// Method names, so call sites never spell one by hand.
    enum Method {
        static let ping = "ping"
        static let complete = "complete"
        static let chat = "chat"
        static let providersList = "providers/list"
        static let credentialsSet = "credentials/set"
        static let credentialsGet = "credentials/get"
        static let credentialsDelete = "credentials/delete"
        static let oAuthLogin = "oauth/login"
        static let configSetBaseUrl = "config/setBaseUrl"
        static let configSetLocalUrl = "config/setLocalUrl"
        static let modelsRefresh = "models/refresh"
        static let promptsCompose = "prompts/compose"
        static let wordLookupsList = "catalog/wordLookups/list"
        static let wordLookupsSave = "catalog/wordLookups/save"
        static let wordLookupsDelete = "catalog/wordLookups/delete"
        static let wordLookupsClear = "catalog/wordLookups/clear"
        static let cancelRequest = "$/cancelRequest"
        static let toolExecute = "tool/execute"
        static let oAuthPrompt = "oauth/prompt"
        static let chatDelta = "chat/delta"
        static let chatThinking = "chat/thinking"
        static let chatAssistant = "chat/assistant"
        static let oAuthNotify = "oauth/notify"
    }

    // MARK: ping
    /// Handshake. The shell refuses to proceed on a protocol mismatch.
    struct PingParams: Encodable {
        init() {}
    }
    struct PingResult: Decodable {
        var `protocol`: Int
        var backend: String
    }

    // MARK: complete
    /// One-shot completion. Streams chat/delta, resolves when finished.
    struct CompleteParams: Encodable {
        var providerId: String
        var model: String
        var system: String?
        var messages: [WireMessage]
        var maxTokens: Int?
        /// Explicit key for Test Connection, before anything is saved.
        var apiKey: String?
        var baseUrl: String?
    }
    struct CompleteResult: Decodable {
        var stopReason: String
    }

    // MARK: chat
    /// The agentic loop. Streams chat/* notifications and calls tool/execute back.
    struct ChatParams: Encodable {
        var providerId: String
        var model: String
        var system: String?
        var messages: [WireMessage]
        var tools: [WireToolDef]?
        var maxTokens: Int?
        var reasoning: String?
        var maxIterations: Int?
    }
    struct ChatResult: Decodable {
        var stopReason: String
    }

    // MARK: providers/list
    struct ProvidersListParams: Encodable {
        init() {}
    }
    struct ProvidersListResult: Decodable {
        var providers: [BackendProviderSummary]
    }

    // MARK: credentials/set
    struct CredentialsSetParams: Encodable {
        var providerId: String
        var key: String
    }
    struct CredentialsSetResult: Decodable {
        init() {}
    }

    // MARK: credentials/get
    struct CredentialsGetParams: Encodable {
        var providerId: String
    }
    struct CredentialsGetResult: Decodable {
        /// null when the provider has no key stored.
        var apiKey: String?
    }

    // MARK: credentials/delete
    struct CredentialsDeleteParams: Encodable {
        var providerId: String
    }
    struct CredentialsDeleteResult: Decodable {
        init() {}
    }

    // MARK: oauth/login
    /// Streams oauth/notify and calls oauth/prompt back for user input.
    struct OAuthLoginParams: Encodable {
        var providerId: String
    }
    struct OAuthLoginResult: Decodable {
        init() {}
    }

    // MARK: config/setBaseUrl
    struct ConfigSetBaseUrlParams: Encodable {
        var providerId: String
        /// Absent clears the override.
        var baseUrl: String?
    }
    struct ConfigSetBaseUrlResult: Decodable {
        init() {}
    }

    // MARK: config/setLocalUrl
    struct ConfigSetLocalUrlParams: Encodable {
        var providerId: String
        var baseUrl: String
    }
    struct ConfigSetLocalUrlResult: Decodable {
        init() {}
    }

    // MARK: models/refresh
    struct ModelsRefreshParams: Encodable {
        var providerId: String?
    }
    struct ModelsRefreshResult: Decodable {
        var message: String?
    }

    // MARK: prompts/compose
    /// The static half of the system prompt: base.md plus the named mixins. The shell appends live context afterwards -- that half cannot be a file.
    struct PromptsComposeParams: Encodable {
        /// Mixin names, without .md, in the order they should appear.
        var mixins: [String]?
    }
    struct PromptsComposeResult: Decodable {
        /// Empty when no prompt files were found.
        var text: String
        /// Mixins that existed and were included.
        var used: [String]
        /// Every mixin this build carries.
        var available: [String]
    }

    // MARK: catalog/wordLookups/list
    /// One document's lookups, or every one when itemId is absent. Newest first.
    struct WordLookupsListParams: Encodable {
        var itemId: String?
    }
    struct WordLookupsListResult: Decodable {
        var lookups: [CatalogWordLookup]
    }

    // MARK: catalog/wordLookups/save
    /// Insert, replacing any prior lookup of the same word in the same document.
    struct WordLookupsSaveParams: Encodable {
        var lookup: CatalogWordLookup
    }
    struct WordLookupsSaveResult: Decodable {
        init() {}
    }

    // MARK: catalog/wordLookups/delete
    struct WordLookupsDeleteParams: Encodable {
        var `id`: String
    }
    struct WordLookupsDeleteResult: Decodable {
        init() {}
    }

    // MARK: catalog/wordLookups/clear
    /// Clear one document's history, or all of it when itemId is absent.
    struct WordLookupsClearParams: Encodable {
        var itemId: String?
    }
    struct WordLookupsClearResult: Decodable {
        init() {}
    }

    // MARK: $/cancelRequest
    /// LSP's spelling. The peer fails the named request and anything it spawned.
    struct CancelRequestParams: Encodable {
        var `id`: String
    }

    // MARK: tool/execute
    /// The shell runs the tool and answers. Tools read local app state, so they cannot run in the sidecar.
    struct ToolExecuteParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var name: String
        var args: [String: JSONFragment]
    }
    struct ToolExecuteResult: Encodable {
        var content: String
        var isError: Bool?
    }

    // MARK: oauth/prompt
    /// Asks the shell for one piece of user input during a login.
    struct OAuthPromptParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var promptType: String
        var message: String
        var placeholder: String?
        var options: [BackendPromptOption]?
    }
    struct OAuthPromptResult: Encodable {
        /// Absent means cancelled.
        var value: String?
    }

    // MARK: chat/delta
    struct ChatDeltaParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var text: String
    }

    // MARK: chat/thinking
    struct ChatThinkingParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var text: String
    }

    // MARK: chat/assistant
    /// Authoritative snapshot of one iteration's assistant message.
    struct ChatAssistantParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var text: String
        var thinking: String?
        var toolCalls: [BackendToolCall]
    }

    // MARK: oauth/notify
    struct OAuthNotifyParams: Decodable {
        /// Id of the request this belongs to.
        var token: String
        var kind: String
        var message: String?
        var url: String?
        var userCode: String?
        var verificationUri: String?
    }

}
