// Generated by protocol/generate.ts from protocol/schema.ts — DO NOT EDIT.
// Run `pnpm protocol:generate` after changing the schema.

import Foundation

enum GeneratedProtocol {
    static let version = 2
}

/// Every command the shell can send. One flat struct: `type` selects which
/// fields are meaningful, and JSONEncoder omits the nils.
struct BackendCommand: Encodable {
    var id: String
    var type: String
    /// complete, chat, set_api_key, get_api_key, delete_credential, oauth_login, set_base_url, set_local_url, refresh_models
    var providerId: String?
    /// complete, chat
    var model: String?
    /// complete, chat
    var system: String?
    /// complete, chat
    var messages: [WireMessage]?
    /// complete, chat
    var maxTokens: Int?
    /// complete
    var apiKey: String?
    /// complete, set_base_url, set_local_url
    var baseUrl: String?
    /// chat
    var tools: [WireToolDef]?
    /// chat
    var reasoning: String?
    /// chat
    var maxIterations: Int?
    /// tool_result
    var callId: String?
    /// tool_result
    var content: String?
    /// tool_result
    var isError: Bool?
    /// set_api_key
    var key: String?
    /// oauth_prompt_result
    var promptId: String?
    /// oauth_prompt_result
    var value: String?
}

/// Every event the backend can emit. Decoding is lenient by design: an
/// unknown field is ignored, and a field belonging to another event type is nil.
struct BackendEvent: Decodable {
    var id: String
    var type: String  // response | delta | thinking | tool_exec | assistant | oauth_notify | oauth_prompt | done | error
    /// response
    var command: String?
    /// response
    var success: Bool?
    /// response
    var `protocol`: Int?
    /// response
    var backend: String?
    /// response, oauth_notify, oauth_prompt, error
    var message: String?
    /// response
    var providers: [BackendProviderSummary]?
    /// response
    var apiKey: String?
    /// delta, thinking, assistant
    var text: String?
    /// tool_exec
    var callId: String?
    /// tool_exec
    var name: String?
    /// tool_exec
    var args: [String: JSONFragment]?
    /// assistant
    var thinking: String?
    /// assistant
    var toolCalls: [BackendToolCall]?
    /// oauth_notify
    var kind: String?
    /// oauth_notify
    var url: String?
    /// oauth_notify
    var userCode: String?
    /// oauth_notify
    var verificationUri: String?
    /// oauth_prompt
    var promptId: String?
    /// oauth_prompt
    var promptType: String?
    /// oauth_prompt
    var placeholder: String?
    /// oauth_prompt
    var options: [BackendPromptOption]?
    /// done
    var stopReason: String?
}
